(function(g){var window=this;var qZ=function(a){a.i||(a.i=new g.Bo,g.G(a,a.i));return a.i},rZ=function(a,b){var c=g.V(a.app);
b.event="iv";a.isFullscreen()&&(b.fs=1);b.ux=1;c=c.C;if(c.i){c=c.i;var d={};d.rt=g.pD(c.g).toFixed(3);g.Ta(d,g.qD(c.g));var e=c.g.wb,f=c.g.videoData;e={ns:e.W,html5:"1",el:g.JB(f),ps:e.playerStyle,fexp:e.experiments.experimentIds.join(",")||void 0,feature:f.hs||f.Ci||void 0,ctrl:f.ue||void 0,ytr:f.we||void 0,list:f.playlistId};g.MB(f)&&(e.autoplay="1");f.subscribed&&(e.subscribed=f.subscribed);g.Ta(d,e);delete d.fexp;g.Ta(d,b);d=g.oq(c.g.wb.C+"player_204",d);g.BD(c,d,void 0)}},sZ=function(a){a.N("cardstatechange",
a.ud()&&a.De()?1:0)},tZ=function(a){var b=g.Lh(a);
a=g.Sh(a);return new g.nh(b.x,b.y,a.width,a.height)},uZ=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},vZ=function(a){return"none"!=a.style.display},wZ=function(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);
var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return+e},Qna=function(a){var b=g.Fh(a,"fontSize");
var c=(c=b.match(Nna))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.Md){if(String(c)in Ona)return wZ(a,b);if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in Pna)return a=a.parentNode,c=g.Fh(a,"fontSize"),wZ(a,b==c?"1em":b)}c=g.Rd("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.Xd(c);return b},Rna=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Ck&&a.dataset){if(g.kc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.fd("pollChoiceIndex"))},zZ=function(a){a=g.Ra(a);
delete xZ[a];g.Yb(xZ)&&yZ&&yZ.stop()},AZ=function(){yZ||(yZ=new g.M(function(){Sna()},20));
var a=yZ;a.isActive()||a.start()},Sna=function(){var a=(0,g.H)();
g.Lb(xZ,function(b){BZ(b,a)});
g.Yb(xZ)||AZ()},CZ=function(a,b){g.sf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},DZ=function(a,b,c,d){g.Wn.call(this);
if(!g.Ma(a)||!g.Ma(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.D=0;this.A=null},BZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;EZ(a,a.progress);1==a.progress?(a.g=0,zZ(a),a.Zc(),a.l()):1==a.g&&a.Mr()},EZ=function(a,b){g.Oa(a.C)&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},FZ=function(a,b,c,d,e){DZ.call(this,b,c,d,e);
this.element=a},GZ=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
FZ.call(this,a,b,c,d,e)},Tna=function(a){return Math.pow(a,3)},Una=function(a){return 3*a*a-2*a*a*a},HZ=function(a){g.D.call(this);
this.i=a||window;this.g=[]},Vna=function(a,b,c,d){c=(0,g.x)(c,d||a.i);
b=g.Wr(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},IZ=function(a,b){(0,g.z)(b,function(c){g.es("visualElementShown",{csn:a,
ve:g.Ls(c),eventType:4},g.js,void 0,void 0)})},JZ=function(a,b){(0,g.z)(b,function(c){g.es("visualElementHidden",{csn:a,
ve:g.Ls(c),eventType:8},g.js,void 0,void 0)})},KZ=function(a,b){g.Sf.call(this);
this.Rj=a;this.Wp=b;this[g.uf]=!1},PZ=function(a,b,c,d){KZ.call(this,a,b);
a=this.Wp;b=this.ga();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.Fa(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/Wna(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Wp;a=this.ga();if(d instanceof LZ)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof MZ){b="lg-"+d.u+"-"+d.C+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=NZ(c,"linearGradient",{x1:d.u,y1:d.C,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Ha(d.l)&&(f+=";stop-opacity:"+d.l);f=NZ(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Ha(d.o)&&(f+=";stop-opacity:"+d.o);d=NZ(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=OZ(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},QZ=function(){},RZ=function(a,b){KZ.call(this,a,b)},SZ=function(){this.Ta=[];
this.Ca=[];this.Sd=[]},m_=function(a,b,c,d){var e=a.xd[0]-b*Math.cos(g.td(d))+b*Math.cos(g.td(d+90)),f=a.xd[1]-c*Math.sin(g.td(d))+c*Math.sin(g.td(d+90));
a.Ta.push(3);a.Ca.push(1);a.Sd.push(b,c,d,90,e,f);a.Vk=!1;a.xd=[e,f]},Yna=function(a,b){for(var c=a.Sd,d=0,e=0,f=a.Ta.length;e<f;e++){var k=a.Ta[e],l=Xna[k]*a.Ca[e];
b(k,c.slice(d,d+l));d+=l}},A_=function(a,b,c,d){PZ.call(this,a,b,c,d)},B_=function(a,b){this.g=a;
this.i=b},C_=function(a,b,c,d,e){g.ho.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.I=d||null},Wna=function(a){var b=a.Gj();
return b?b.width/(a.l?new g.wd(a.l,a.I):a.Gj()).width:0},MZ=function(a,b,c,d,e,f,k,l){this.u=a;
this.C=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Ea(k)?k:null;this.o=g.Ea(l)?l:null},LZ=function(a,b){this.F=a;
this.H=null==b?1:b},D_=function(a,b){KZ.call(this,a,b)},E_=function(a,b,c,d){PZ.call(this,a,b,c,d)},F_=function(a,b,c,d,e){C_.call(this,a,b,c,d,e);
this.g={};this.R=g.Od&&!g.od(526);this.P=new g.an(this)},NZ=function(a,b,c){a=a.M.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},G_=function(a,b,c,d){b=NZ(a,"path",{d:Zna(b)});
c=new E_(b,a,c,d);a.o.ga().appendChild(c.ga())},Zna=function(a){var b=[];
Yna(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,180<Math.abs(e)?1:0,0<e?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},OZ=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+$na++;c.setAttribute("id",d);a.g[b]=d;a.C.appendChild(c);return d},aoa=function(){H_||(H_=new g.Fg(400),H_.start());
return H_},I_=function(a,b){function c(l){return l.baseUrl}
function d(l){if(l){var m=l.simpleText;if(m)return m;if(l.runs)return(0,g.B)(l.runs,function(n){return n.text}).join("")}}
function e(l){if(l){var m=[],n=l.videoId;n&&m.push("v="+n);(n=l.playlistId)&&m.push("list="+n);(l=l.startTimeSeconds)&&m.push("t="+l);return"/watch?"+m.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.B)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;a.trackingParams&&(f.visualElement=g.Ks(a.trackingParams));var k=(0,g.B)(a.elements||[],function(l,m){var n=l.endscreenElementRenderer;if(!n)return null;var p={},r=n.style,u=n.endpoint||{};p.id="element-"+m;p.type=r;p.title=d(n.title);p.metadata=d(n.metadata);p.callToAction=d(n.callToAction);p.jv=n.image;p.left=parseFloat(n.left);p.width=parseFloat(n.width);p.top=parseFloat(n.top);p.aspectRatio=
parseFloat(n.aspectRatio);p.startMs=parseInt(n.startMs,10);p.endMs=parseInt(n.endMs,10);p.clickUrls=(0,g.B)(u.loggingUrls||[],c);p.El=g.Tb(n,"title","accessibility","accessibilityData","label");p.impressionUrls=(0,g.B)(n.impressionUrls||[],c);p.VD=(0,g.B)(n.hovercardShowUrls||[],c);p.Xb={itct:n.trackingParams};p.visualElement=g.Ks(n.trackingParams);if("VIDEO"==r)p.targetUrl=u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Cm=!1,p.Zn=b,p.videoDuration=d(n.videoDuration);else if("PLAYLIST"==r)p.targetUrl=
u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Cm=!1,p.Zn=b,p.playlistLength=d(n.playlistLength);else if("CHANNEL"==r){if(r=g.Tb(u,"browseEndpoint","browseId"))p.channelId=r,p.targetUrl="/channel/"+r;p.Cm=!1;p.Zn="new";p.isSubscribe=!!n.isSubscribe;if(p.isSubscribe){a:{if(r=n.hovercardButton)if(r=r.subscribeButtonRenderer){u=d(r.unsubscribedButtonText);var A=d(r.subscribedButtonText);if(r.subscribed){var C=d(r.subscriberCountWithUnsubscribeText);var E=d(r.subscriberCountText)}else C=d(r.subscriberCountText),
E=d(r.subscriberCountWithSubscribeText);var F=null;if(n.signinEndpoint&&(F=g.Tb(n,"signinEndpoint","webNavigationEndpointData","url"),!F)){n=void 0;break a}if(u&&(A||F)){n={subscribed:r.subscribed,subscribeText:u,subscribeCount:C,unsubscribeText:A,unsubscribeCount:E,enabled:r.enabled,signinUrl:F,classic:n.useClassicSubscribeButton};break a}}n=void 0}p.subscribeButton=n}else p.subscribersText=d(n.subscribersText)}else"WEBSITE"==r&&(p.targetUrl=g.Tb(u,"urlEndpoint","url"),p.Cm=!0,p.Zn="new",p.iconUrl=
n.icon.thumbnails[0].url);return p});
f.elements=(0,g.Yd)(k,function(l){return!!l});
return f},J_=function(a){g.yK.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.C={};this.A=this.l=null;this.I=[];a=g.X(a);this.P=g.Fy(a)||g.Hy(a);this.DA=!0;this.D=0;this.F=new g.Mn;this.u=new g.vs(this);g.G(this,this.u);this.u.K(this.player,g.ND("creatorendscreen"),this.QE);this.u.K(this.player,"crx_creatorendscreen",this.RE);this.u.K(this.player,"resize",this.Wa);this.u.K(window,"focus",this.KL);this.load();var b=g.Sd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},K_=function(a){return a.player.getVideoData().Nb?"current":a.P?"new":"current"},L_=function(a){return"creator-endscreen-editor"===a},M_=function(a,b){g.gK(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.C={};0<a.I.length&&(a.I.forEach(function(l){l.dispose()}),a.I.length=0);
a.D=0;if((a.i=b)&&b.elements){boa(a);c=[];var d=new g.KD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.X(a.player).g||(a.l=new g.W({B:"div",G:"ytp-ce-shadow"}),g.kK(a.player,a.l.element,4),a.A=new g.TP(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=coa(a,e);a.g[e.id]=f;a.C[e.id]=e;g.kK(a.player,f.element,4);var k=new g.KD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);doa(a,f,e)}g.dK(a.player,
c);a.Wa()}},boa=function(a){var b=g.$s(),c=g.at();
c&&b&&a.i.visualElement&&g.Ms(c,b,[a.i.visualElement],void 0)},coa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={B:"div",V:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.El||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:N_(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:O_(a,b.targetUrl),tabindex:"-1"},J:[{B:"div",V:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Nn(a.F,b.title||"")},T:b.title},{B:"div",G:"ytp-ce-video-duration",T:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={B:"div",V:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.El||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:N_(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:O_(a,b.targetUrl),tabindex:"-1"},J:[{B:"div",V:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Nn(a.F,b.title||"")},T:b.title},{B:"div",G:"ytp-ce-playlist-count",J:[{B:"div",
G:"ytp-ce-playlist-icon"},{B:"div",G:"ytp-ce-playlist-count-text",T:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={B:"div",V:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.El||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",J:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",
J:[{B:"div",G:"ytp-ce-expanding-overlay-body",J:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{B:"a",V:["ytp-ce-channel-title","ytp-ce-link"],L:{href:O_(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Nn(a.F,b.title||"")},T:b.title},b.subscribeButton?{B:"div",G:"ytp-ce-subscribe-container",J:[{B:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{B:"div",G:"ytp-ce-channel-subscribers-text",T:b.subscribersText}:"",b.metadata?{B:"div",V:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],T:b.metadata}:""]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:N_(b)}]};c=new g.W(c);var d=g.Fd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.J(d,"ytp-ce-subscribe-button");if(g.X(a.player).g){var e=null;var f=b.Xb.itct}else e="endscreen",f=null;e=new g.MV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.I.push(e)}break;case "WEBSITE":c={B:"div",V:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.El||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",J:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",J:[{B:"div",G:"ytp-ce-expanding-overlay-body",
J:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{B:"div",G:"ytp-ce-website-title",L:{dir:g.Nn(a.F,b.title||"")},T:b.title},{B:"div",G:"ytp-ce-website-metadata",T:b.metadata},{B:"a",V:["ytp-ce-website-goto","ytp-ce-link"],L:{href:O_(a,b.targetUrl),target:"_blank",tabindex:"-1"},T:b.callToAction}]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:N_(b)},{B:"div",G:"ytp-ce-expanding-icon",L:P_(b.iconUrl)}]},c=new g.W(c)}b.g&&g.J(c.element,"ytp-ce-placeholder");return c},N_=function(a){if(a.jv)var b=
a.jv.thumbnails;
return P_(b?b[b.length-1].url:null)},P_=function(a){return a?{style:"background-image: url("+a+")"}:{}},doa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ca("mouseenter",(0,g.x)(a.Xq,a,b,c));b.ca("mouseleave",(0,g.x)(a.Rr,a,b,c));g.X(a.player).g||b.ca("click",(0,g.x)(function(l){g.J(l.element,"ytp-ce-element-hover")},a,b));
b.ca("click",(0,g.x)(a.Jy,a,c));b.ca("keypress",(0,g.x)(a.Jy,a,c));b.ca("focus",(0,g.x)(function(l,m){this.Xq(l,m)},a,b,c));
b.ca("blur",(0,g.x)(function(l,m){this.Rr(l,m)},a,b,c));
b.ca("touchstart",(0,g.x)(a.Xq,a,b,c));var f=g.Hd("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Tn(b.element,"ytp-ce-element-hover");g.Tn(b.element,"ytp-ce-force-expand")});
b.ca("keydown",(0,g.x)(function(l,m){this.DA=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.D+=n;0<this.D?(g.J(l.element,"ytp-ce-force-expand"),Q_(this,m.id,!0)):(g.Tn(l.element,"ytp-ce-force-expand"),g.Tn(l.element,"ytp-ce-element-hover"),Q_(this,m.id,!1))},a,b,c);
a=(0,g.x)(function(l,m){m&&(l.ca("blur",function(){vZ(m)&&this.DA&&m.focus()}),l.K(m,"focus",d),l.K(m,"blur",e))},a,b);
a(g.Hd("ytp-sb-subscribe",b.element));a(g.Hd("ytp-sb-unsubscribe",b.element));b.ca("focus",d);b.ca("blur",e)},O_=function(a,b){var c=g.X(a.player);
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.kz(c)+b}else return"";return b},Q_=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.K(a.g[d].element,"ytp-ce-element-shadow-show",c)},R_=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||L_(g.X(a.player).playerStyle))c&&c();else{b=eoa(a,b);var e=0,f=!1,k=new g.M(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.$q(b[a],d)}},S_=function(a,b,c){R_(a,b.clickUrls,c);
(a=g.at())&&b.Cm&&g.Os(a,b.visualElement)},eoa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(foa(b[e],c));return d},foa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},T_=function(a){return g.Ma(a)&&a.length?a[0]:a},U_=function(a){var b=/.+/;
return g.Fa(a)&&null!=b&&null!=a&&a.match(b)?a:""},V_=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},W_=function(a){return g.Fa(a)?a:""},X_=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Y_=function(a,b){return"true"==a||"false"==a?"true"==a:b},Z_=function(a,b){return g.Fa(a)?parseFloat(a):b},$_=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.qd(a,b,c);if(a>=b&&a<=c)return a}return e},goa=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.z)(a,function(d){d=parseFloat(d);0>d&&(c=-c);b=60*b+Math.abs(d)});
return c*b},a0=function(a,b){if(null==a)return null;
if(g.Na(a)){var c=[];(0,g.z)(a,function(e){(e=b(e))&&c.push(e)});
return c}var d=b(a);return d?[d]:[]},hoa=function(a){function b(c){return null!=c&&!isNaN(c)}
return(a=a?new g.kh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},ioa=function(a){function b(c){return(0,g.Yd)(c.split(/ +/),function(d){return""!=d})}
return null==a?[]:b(a)},joa=function(a){this.externalId=a},koa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},b0=function(a){if(!a)return null;
var b=g.Dc(W_(a.value));b=g.Ac(b);if(!b)return null;var c=X_(a.target,loa,"current");return null==c?null:new koa(b,c,Y_(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},c0=function(a){return a.value?a.value:null},moa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},poa=function(a){if(!a)return null;
var b=X_(a.type,noa),c=X_(a.trigger,ooa),d=T_(a.url);d=b0(d?d:null);a=T_(a.subscribeData);var e=a?a:null;e?(a=W_(e.external_user_id),e=W_(e.subscription_token),a=a&&e?new joa(a):null):a=null;return b?new moa(b,c,d,a):null},d0=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},e0=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},f0=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.Vi=c;this.l=d;this.t=e;this.u=f;this.A=k;this.C=l;this.o=m;this.i=n;this.g=p},g0=function(a,b){if(!a)return null;
var c=Z_(a.x,0),d=Z_(a.y,0),e=Z_(a.w,0),f=Z_(a.h,0),k=goa(a.t),l=Z_(a.d,0),m=Z_(a.px,0),n=Z_(a.py,0),p=Z_(a.scaleSlope,1),r=Z_(a.scaleSlopeX,p);p=Z_(a.scaleSlopeY,p);var u=X_(a.scaleDimension,qoa,"xy");return b(c,d,e,f,k,l,m,n,r,p,u)},j0=function(a,b){var c=h0(b,i0(a,new g.nh(a.x,a.y,a.Vi,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.qd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.qd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},i0=function(a,b,c){var d=a.A,e=a.C,f=a.g?a.g:"xy",k=d0(c,a.o,f);
a=e0(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.nh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},k0=function(a){return a?g0(a,function(b,c,d,e,f,k,l,m,n,p,r){return new f0(b,c,d,e,f,k,l,m,n,p,r)}):null},l0=function(a,b){this.g=a;
this.i=b||null},h0=function(a,b){var c=a.i?j0(a.i,new l0(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.ud?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ha(c)&&(d.top+=c));return d},m0=function(a,b,c,d,e,f,k,l,m,n,p,r,u){f0.call(this,a,b,c,d,e,l,m,n,p,r,u);
this.D=f;this.F=k},roa=function(a){if(!a)return null;
var b=Z_(a.sx,0),c=Z_(a.sy,0);return g0(a,function(d,e,f,k,l,m,n,p,r,u,A){return new m0(d,e,f,k,l,b,c,m,n,p,r,u,A)})},soa=function(a,b,c,d,e,f,k,l,m,n,p,r,u,A){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=p;this.effects=r;this.cornerRadius=u;this.u=A},n0=function(a){if(!a)return null;
var b=V_(a.fgColor,"#1A1A1A"),c=V_(a.bgColor,"#FFF"),d=V_(a.borderColor,"#000"),e=$_(a.borderWidth,0,5,!1,0),f=$_(a.bgAlpha,0,1,!1,.8),k=V_(a.highlightFontColor,"#F2F2F2"),l=$_(a.highlightWidth,0,5,!1,3),m=W_(a.textAlign),n=$_(a.textSize,3.3,30.1,!0,3.6107),p=W_(a.fontWeight),r=hoa(a.padding),u=ioa(a.effects),A=$_(a.cornerRadius,0,10,!0,0);a=T_(a.gradient);if(a=a?a:null){var C=$_(a.x1,0,100,!0,0),E=$_(a.y1,0,100,!0,0),F=$_(a.x2,0,100,!0,100),L=$_(a.y2,0,100,!0,100),aa=V_(a.color1,"#FFF"),qa=V_(a.color2,
"#000");a=new toa(C,E,F,L,aa,qa,$_(a.opacity1,0,100,!0,100),$_(a.opacity2,0,100,!0,0))}else a=null;return new soa(b,c,d,e,f,k,l,m,n,p,r,u,A,a)},toa=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.C=k;this.D=l},uoa=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},woa=function(a){if(!a)return null;
var b=X_(a.type,voa,"rect"),c=a0(a.rectRegion,k0),d=a0(a.anchoredRegion,roa);a=a0(a.shapelessRegion,k0);return new uoa(b,c,d,a)},o0=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},xoa=function(a,b){this.i=a;
this.g=b},yoa=function(a,b){this.state=a;
this.ref=b},p0=function(a){if(!a)return null;
var b=X_(a.state,zoa);a=U_(a.ref);return b?new yoa(b,a):null},Aoa=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},Boa=function(a){if(!a)return null;
var b=a0(a.condition,p0),c=a0(a.notCondition,p0),d=Y_(a.show_delay,!1);a=Y_(a.hide_delay,!1);return b||c?new Aoa(b,c,d,a):null},Coa=function(a,b,c){(0,g.z)(a.g,g.Sa(b,!1),c);
(0,g.z)(a.l,g.Sa(b,!0),c)},q0=function(a,b,c,d,e,f,k,l,m,n,p,r,u,A){this.id=a;
this.author=b;this.type=c;this.style=d;this.l=e;this.segment=f;this.i=k||[];this.A=l||[];this.g=m;this.u=n;this.o=p;this.data=r;this.bb=u;this.itct=A},Foa=function(a){if(!a)return null;
var b=U_(a.id),c=U_(a.author),d=X_(a.type,Doa),e=X_(a.style,r0),f=W_(T_(a.TEXT)),k=W_(a.data);k=0!=k.length?JSON.parse(k):{};var l=T_(a.segment);var m=l?l:null;m?(U_(m.timeRelative),l=U_(m.spaceRelative),l=(m=a0(m.movingRegion,woa))?new xoa(l,m):null):l=null;m=a0(a.action,poa);var n=a0(a.trigger,Boa),p=T_(a.appearance);(p=n0(p?p:null))||(p=n0({}));var r=X_(a.coordinate_system,Eoa,"video_relative"),u=Y_(a.closeable,!0),A=W_(a.log_data);a=W_(a.itct);return b&&d?new q0(b,c,d,e,f,l,m,n,p,r,u,k,A,a):null},
t0=function(a){return s0(a,function(b){return"click"==b.trigger})},s0=function(a,b){return(0,g.Mj)(a.i,b,void 0)},Goa=function(a,b,c){(0,g.z)(a.i,b,c)},Hoa=function(a,b){return g.Ya(a.i,b,void 0)},u0=function(a,b,c){(0,g.z)(a.A,b,c)},Ioa=function(a,b){(0,g.B)(a.A,b,void 0)},w0=function(a){return(a=v0(a))?o0(a):null},v0=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},x0=function(a,b){var c=w0(a);
return c&&b?e0(b,c.i,c.g?c.g:"xy"):1},z0=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;Coa(b,function(d,e){var f=y0(e.state,e.ref);this.i.subscribe(f,(0,g.x)(this.o,this,f,d));this.g[f]=d},this)},y0=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},A0=function(){this.g=!1;
this.u=this.i=null},B0=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new F_(b,c,void 0,void 0,void 0),a.i=b,a.i.cq(),a.u=g.Rd("DIV"),a.u.appendChild(a.i.ga()));
return a.i},C0=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Lb(b,function(f,k){d.setAttribute(k,f)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},D0=function(a,b){var c=g.go(g.fo.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},Joa=function(a,b){var c=D0(a,C0("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=D0(a,C0("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},C0("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=D0(a,C0("feComposite",{"in":c,in2:b,operator:"in"}));return D0(a,C0("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},Koa=function(a,b){var c=D0(a,C0("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=D0(a,C0("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=D0(a,C0("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=D0(a,C0("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=D0(a,C0("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=D0(a,C0("feComposite",{operator:"out","in":c,in2:d}));return D0(a,C0("feComposite",{operator:"over","in":b,in2:c}))},Loa=function(a,b){return b},Moa=function(a){var b=
C0("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.z)(a,function(d){a:{switch(d){case "bevel":d=Joa;break a;case "dropshadow":d=Koa;break a}d=Loa}c=d(b,c)});
return b},Noa=function(a){a=(0,g.Yd)(a,function(b){return b in E0});
g.rb(a,function(b,c){return E0[b]-E0[c]});
return a},Ooa=function(a){return g.Ya(a,function(b){return"dropshadow"==b})?new g.kh(0,7,7,0):new g.kh(0,0,0,0)},F0=function(a,b,c){var d=new SZ;
d.moveTo(a.left+b+c,a.top+c);d.Zb(a.left+a.width-b-c,a.top+c);m_(d,b,b,-90);d.Zb(a.left+a.width-c,a.top+a.height-b-c);m_(d,b,b,0);d.Zb(a.left+b+c,a.top+a.height-c);m_(d,b,b,90);d.Zb(a.left+c,a.top+b+c);m_(d,b,b,180);d.close();return d},G0=function(a,b,c,d){var e=a.u;
e?a=new MZ(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.C,e.D):(b=a.g,a=new LZ(a.bgColor,d?Math.max(b,.9):b));return a},H0=function(a,b){var c=g.oh(a),d=Ooa(b);
g.Pa(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.nh(c.left,c.top,c.right-c.left,c.bottom-c.top)},I0=function(a,b,c){if(c.length&&(b=g.Fd(document,"g",void 0,b),b.length)){var d=Noa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=Moa(d),a=0<d.childNodes.length?OZ(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},J0=function(){A0.call(this);
this.o=0},Poa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},K0=function(){A0.apply(this,arguments)},L0=function(){A0.apply(this,arguments)},M0=function(){J0.apply(this,arguments)},N0=function(a,b,c,d,e){g.D.call(this);
this.g=a;this.R=b;this.A=c;this.X=d;this.Z=e;this.F=!1;this.ba=new HZ(this);g.G(this,this.ba);this.M=this.u=this.C=this.P=this.i=null;this.W=!1;this.aa=this.H=this.I=null;this.qn=new g.Al(this.xD,100,this);g.G(this,this.qn);this.D=new g.M(this.ww,500,this);g.G(this,this.D);this.O=this.l=this.o=null},Qoa=function(a,b){var c=(0,g.x)(function(d,e,f){e=f?O0(this,e,(0,g.x)(f,this)):O0(this,e);
this.ba.ca(b,d,e)},a);
c("mouseover","G",a.vx);c("mouseout","F",a.Cg);c("click","D");c("touchend","D")},Roa=function(a){if(a.g.o){if(s0(a.g,function(d){return"close"==d.type}))var b=a.i;
else a.o=g.Rd("DIV","annotation-close-button"),g.Th(a.o,!1),g.Fp(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(d){d.stopPropagation()};
a.ba.ca(b,"click",O0(a,"E",c));a.ba.ca(b,"touchend",O0(a,"E",c))}},O0=function(a,b,c){return(0,g.x)(function(d){if(this.Z)c&&c(d);
else if(d.event.target instanceof Element){var e=d.event.target;g.Th(e,!1);try{var f=document.elementFromPoint(d.event.clientX,d.event.clientY);if(g.ge(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(d.event.type,d.event.bubbles,d.event.cancelable,d.event.view,d.event.detail,d.event.screenX,d.event.screenY,d.event.clientX,d.event.clientY,d.event.ctrlKey,d.event.altKey,d.event.shiftKey,d.event.metaKey,d.event.button,d.event.relatedTarget);f.dispatchEvent(k)}}finally{g.Th(e,
!0)}}e=tZ(d.target);d=new g.ud(d.clientX,d.clientY);"F"==b&&e.contains(d)||this.X.N(b,this.g)},a)},R0=function(a){if(a.i||a.l){var b=w0(a.g);
if(b){var c=P0(a);if(a.i){b=j0(b,c);var d=g.XJ(a.A).getVideoContentRect();g.Rh(a.i,b.width,b.height);g.Hh(a.i,b.left,b.top);a.P=new g.nh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=w0(a.g))&&d?d0(d,e.o,e.g?e.g:"xy"):1;var f=x0(a.g,d);d=a.g.g;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.kh(d,d,d,d));d=new g.kh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.C&&(a.C.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.XJ(a.A).getVideoContentRect();var p=g.bK(a.A);g.ph(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.g.u&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=Q0(a,23,b,d,e);if(a.o){var r=43-f.width;0<r&&(b.left+f.left-r>n.left&&(f.left-=r),f.width+=r)}r=f;g.Rh(a.u,f.width,f.height);g.Hh(a.u,f.left,f.top)}a.o&&(r?b=new g.ud(r.left+
r.width-23-18,a.W?r.top+2:r.top+r.height-18-2):(r=Q0(a,18,b,d,e),b=new g.ud(r.left,r.top),g.Rh(a.o,r.width,r.height)),g.Hh(a.o,b));a.M=new g.nh(a.P.left+r.left,a.P.top+r.top,r.width,r.height);a.I=a.ba.ca(g.XJ(a.A),"mousemove",a.IF,a)}else a.u&&(r=e/f*d.height*4.2/100,r=new g.wd(r,r),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,r=new g.nh(b.width-r.width-e,b.height-r.height-e,r.width,r.height)):r=new g.nh(b.width-r.width-3*d.height/100,(b.height-r.height)/2,r.width,r.height),g.Rh(a.u,
r.width,r.height),g.Hh(a.u,r.left,r.top)),a.o&&(r=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Hh(a.o,r&&e?new g.ud(b.width-9,-9):r?new g.ud(b.width-9,45<b.height?9:b.height-9):e?new g.ud(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.ud(45<b.width?b.width-9-18:-9,b.height-9):new g.ud(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.g;c.style.color="highlightText"==a.g.style?b.A:b.i;r=g.XJ(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
x0(a.g,r)/100+"px";r=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==r||"highlightText"==r?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;r=(b=g.Hd("annotation-link-icon",a))?vZ(b):!1;e=(d=g.Hd("annotation-close-button",a))?vZ(d):!1;r&&g.Th(b,!1);e&&g.Th(d,!1);m=f="";if(n=g.Hd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=Qna(a);p=5;for(var u=Math.floor(k/2);u;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+u,k)):l=Math.max(l-u,p),u=Math.floor(u/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.Th(d,!0);r&&g.Th(b,!0)}}}},Q0=function(a,b,c,d,e){var f=0<e;
b=new g.nh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.J(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.J(a.i,"annotation-extend-up"),a.W=!0);return b},S0=function(a){return"label"!=a.g.style||a.l.g},P0=function(a){var b=g.XJ(a.A).getVideoContentRect();
if("player_relative"==a.g.u){var c=g.XJ(a.A).getPlayerSize();b=new g.nh(-b.left,-b.top,c.width,c.height)}else b=new g.nh(0,0,b.width,b.height);return new l0(b,a.O?w0(a.O):null)},T0=function(a,b){return b?new g.nh(a.x+b.left,a.y+b.top,b.width,b.height):null},U0=function(a,b,c){g.D.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;Soa(b,a)},Soa=function(a,b){Ioa(a,function(c){return new z0(a.id,c,b)})},V0=function(a){a.i.unsubscribe("resize",a.tx,a);
a.i.unsubscribe("onVideoAreaChange",a.iz,a)},W0=function(a){a.g&&(a.g.stop(),a.g=null)},X0=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Toa=function(a,b){this.merchant=a;
this.price=b},Uoa=function(a){this.g=a;
this.i={}},Voa=function(a){var b={};
b=(b["iv-event"]=1,b);rZ(a.g,b)},a1=function(a,b,c,d){if(b){var e=Y0(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=Z0(a,"cta_annotation_shown",e,c);$0(a,e,Woa(b,d))}},b1=function(a,b,c,d,e,f){if(b){var k=Y0(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.fc(k,d);b=Z0(a,"cta_annotation_clicked",k,e);$0(a,k,b,c,f)}},c1=function(a,b){if(b){var c=Y0(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=Z0(a,"cta_annotation_closed",c);$0(a,c,d)}},Woa=function(a,b){return b?(0,g.B)(a,g.Sa(function(c,d){return g.dn(d,c)},b)):a},Z0=function(a,b,c,d){d=d?g.ib(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Q(g.X(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.tu){if((b=a.tu[b])&&g.bv(b)){a=g.Xc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.Hn){b=g.oq(a.Hn,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},$0=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.z)(c||[],function(n){f++;
g.$q(n,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));rZ(a.g,b)},Y0=function(a,b){var c={};
if(b){var d=new g.Tm(b);(0,g.z)(d.Hd(),function(e){c[e]=escape(d.get(e,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.X(a.g).playerStyle;return c},d1=function(a,b,c,d,e){e=Y0(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;$0(a,e,d)},e1=function(a,b,c,d){c&&(c=Y0(a,c),c["iv-event"]=b,$0(a,c,d))},Xoa=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.wb=c;this.videoData=d;this.logger=e;this.Y=f;this.i=k},f1=function(a,b){this.g=a;
this.o=b;this.i=new g.Mn},Zoa=function(a,b){var c=[];
(0,g.z)(b.choices,function(k){c.push(Yoa(this,b,k))},a);
var d={B:"ul",L:{role:"radiogroup"},J:c},e={};b.Pd&&(e["aria-label"]=g.hN("$POLL_TITLE \u2013 \u043f\u0440\u0438\u0458\u0430\u0432\u0438\u0442\u0435 \u0441\u0435 \u0434\u0430 \u0431\u0438\u0441\u0442\u0435 \u043c\u043e\u0433\u043b\u0438 \u0434\u0430 \u0433\u043b\u0430\u0441\u0430\u0442\u0435.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{B:"div",G:"iv-card-content",J:[g1(a,"h2",e,b.title),{B:"form",J:[{B:"fieldset",J:[d]}]}]}];b.Pd&&(f.push("iv-card-unavailable"),d.push({B:"div",V:["iv-card-sign-in"],
J:[{B:"h2",T:"\u0416\u0435\u043b\u0438\u0442\u0435 \u043b\u0438 \u0434\u0430 \u0433\u043b\u0430\u0441\u0430\u0442\u0435?"},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:c0(b.Pd)},J:[{B:"span",V:["iv-button-content"],T:"\u041f\u0440\u0438\u0458\u0430\u0432\u0438 \u043c\u0435"}]}]}));f=new g.W({B:"div",V:f,J:d});d=f.element;h1(b,d);Vna(a.g.g,d,g.Sa(a.u,b),a);(0,g.z)(g.Gd("iv-card-poll-choice-input",d),function(k){this.g.g.ca(k,"focus",g.Sa(this.l,!0));this.g.g.ca(k,"blur",g.Sa(this.l,!1))},
a);
b.Pd&&(d=g.Hd("iv-card-sign-in-button",d),a.o(d,b.Pd,b.id,b.Xb,b.bb,b.qd.click,5));return f},l1=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.XM?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.gE&&b.yu?{B:"span",V:d,L:e,T:b.yu}:"";c={B:"div",V:["iv-card",c],J:[{B:"a",G:"iv-click-target",L:{href:c0(b.url)},J:[i1(b.Zk,d?{B:"div",G:"iv-card-image-text",J:[d,b.priceText]}:""),{B:"div",G:"iv-card-content",J:[{B:"h2",G:"iv-card-primary-link",T:b.title},j1(a,b)]}]}]};c=new g.W(c);k1(a,c,b);return c},m1=function(a,b){return b.customMessage?g1(a,"div",
"iv-card-message",b.customMessage):""},i1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{B:"div",G:"iv-card-image",L:{style:c},J:d}},j1=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.z)(b.metaInfo,function(d){c.push(g1(this,"li","",d))},a);
return{B:"ul",G:"iv-card-meta-info",J:c}},Yoa=function(a,b,c){return{B:"li",
G:X0(b,c.index),J:[{B:"label",J:[{B:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.id.replace(/[^a-z0-9-]/gi,"-")+c.index.toString(),value:c.index.toString(),"data-poll-choice-index":c.index.toString()}},{B:"span",G:"iv-card-poll-choice-text",J:[{B:"span",G:"iv-card-poll-choice-percent"},g1(a,"span",void 0,c.desc)]}]},{B:"div",G:"iv-card-poll-result",J:[{B:"div",G:"iv-card-poll-result-bar"}]}]}},g1=function(a,b,c,d){c?g.Fa(c)?c={"class":c}:g.Ma(c)&&(c={"class":c.join(" ")}):
c={};
c.dir=g.Nn(a.i,d);return{B:b,L:c,T:d}},n1=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.Zo&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.Zo+");");d.dir=g.Nn(a.i,b.customMessage);var e=[{B:"span",T:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({B:"span",G:"iv-card-link-icon"}));return{B:"div",V:c,L:d,J:e}},h1=function(a,b){var c=0;
(0,g.z)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Hd(X0(a,e.index),b);e=e.count/c;null==a.he&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.he==d);f.getElementsByTagName("input")[0].checked=a.he==d;var k=Math.floor(100*e).toFixed(0),l=g.Hd("iv-card-poll-choice-percent",f);g.be(l,g.hN("$PERCENT%",{PERCENT:k}));f=g.Hd("iv-card-poll-result-bar",f);g.zh(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.he);g.K(b,"iv-card-poll-expanded",
null!=a.he&&1<a.choices.length)},k1=function(a,b,c,d,e){c.Pd&&o1(a,g.Gd("iv-card-sign-in-button",b.element),c,c.Pd,e);
c.url&&o1(a,g.Gd("iv-click-target",b.element),c,c.url,d)},o1=function(a,b,c,d,e){(0,g.z)(b,function(f){if(e){var k=(0,g.x)(function(l){l.stopPropagation();
l.preventDefault();e();return!1},this);
this.g.g.ca(f,"click",k)}else d&&this.o(f,d,c.id,c.Xb,c.bb,c.qd.click,5)},a)},p1=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},r1=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=q1(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},q1=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},$oa=function(a){a=c0(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!r1(a))||(b=g.Qg(g.Sg(5,a))||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.mq(a);if(!b||!b.v)return null;if(b=b.t)return p1(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.kq(a[1]))&&a.t?p1(a.t):-1},s1=function(a){a=c0(a);
a=a.replace(/https?:\/\//g,"");return r1(a)?(a=g.mq(a))&&a.v?a.v:null:null},apa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},t1=function(a,b){return b?b:r1(a)?"current":"new"},u1=function(a,b){g.D.call(this);
this.Ba=a;this.context=b;this.jt=!1;this.X=0},bpa=function(a){return(0,g.H)()-a.X},cpa=function(a,b,c,d,e,f){var k=c0(b);
if(k){var l=t1(k,b.target),m=(0,g.x)(function(){b.g&&this.context.Y.pauseVideo();var p=this.context.videoData.Nb||!1,r=g.mq(k||"");p&&r&&(r.v||r.list)?g.SX(this.context.Y.app,r.v,c,r.list,!1,void 0):g.pL(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=bpa(a);b1(a.context.logger,d,m,n,e,f);r1(k)||(a=g.at(),d=c.itct,a&&d&&g.Os(a,g.Ks(d)))}},x1=function(a,b,c){u1.call(this,b,c);
var d=this;this.i=a;this.R=null;this.W=this.wa=this.u=this.va=!1;this.aa=null;this.M=new g.M(g.Ja,c.wb.fd?4E3:3E3);g.G(this,this.M);this.ka=new g.M(g.Ja);g.G(this,this.ka);this.D=new f1(c,(0,g.x)(this.Li,this),(0,g.x)(this.Nm,this));this.F=new g.W({B:"div",G:"iv-drawer",L:{id:"iv-drawer"},J:[{B:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},J:[{B:"span",G:"iv-drawer-header-text"},{B:"button",V:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"\u0421\u0430\u043a\u0440\u0438\u0458 \u043a\u0430\u0440\u0442\u0438\u0446\u0435",
tabindex:"0"}}]},{B:"div",G:"iv-drawer-content"}]});g.G(this,this.F);this.A=this.F.element;this.ua=new g.TP(this.F,330);g.G(this,this.ua);this.xa=g.Hd("iv-drawer-header-text",this.A);this.o=g.Hd("iv-drawer-content",this.A);this.l=[];this.ma=this.O=this.C=this.Z=this.g=null;this.I=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.wa&&v1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.wa=d.u)&&w1(d)});
this.P=this.H=this.fa=null},dpa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c){var d=b.data.tracking||{};d={XD:d.impression,click:d.click,close:d.close,HM:d.teaser_impression,Ns:d.teaser_click};var e=b.data.tracking_params||{},f=null;switch(c){case "collaborator":d={id:b.id,bb:b.bb,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):
null,de:e.icon?g.Ks(e.icon):null,channelId:b.data.channel_id,customMessage:b.data.custom_message?b.data.custom_message:null,bM:b.data.image_url,title:b.data.title,metaInfo:b.data.meta_info,url:b0({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url})};y1(a,d);break;case "episode":case "movie":d={id:b.id,bb:b.bb,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,
autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):null,de:e.icon?g.Ks(e.icon):null,Zk:b.data.image_url,yu:b.data.badge_symbol||"",priceText:b.data.price_text||"",title:b.data.title,metaInfo:b.data.meta_info,gE:!!b.data.is_paygated,XM:!!b.data.user_has_entitlement,url:b0({target:b.data.target||"new",value:b.data.url})};y1(a,d);break;case "playlist":d={id:b.id,bb:b.bb,timestamp:b.data.timestamp||0,type:b.data.card_type,
teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):null,de:e.icon?g.Ks(e.icon):null,Zk:b.data.image_url,playlistVideoCount:b.data.playlist_video_count,customMessage:b.data.custom_message?b.data.custom_message:null,title:b.data.title,metaInfo:b.data.meta_info,url:b0({pause_on_navigation:b.data.pause_on_navigation,
target:b.data.target||"new",value:b.data.url})};y1(a,d);break;case "poll":d={id:b.id,bb:b.bb,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):null,de:e.icon?g.Ks(e.icon):null,title:b.data.title,choices:b.data.choices,he:b.data.hasOwnProperty("old_vote")?
b.data.old_vote:null,Pd:b.data.signin_url?b0({target:"current",value:b.data.signin_url}):null,gN:b.data.hasOwnProperty("xsrf_token")?b.data.xsrf_token:null};y1(a,d);break;case "productListing":b.data.signin_url&&(f=b0({target:"current",value:b.data.signin_url}));c=[];for(var k=b.data.offers||[],l=0;l<k.length;l++)c.push(new Toa(g.bd(k[l].merchant),g.bd(k[l].price)));d={IQ:!1,id:b.id,bb:b.bb,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,
startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):null,de:e.icon?g.Ks(e.icon):null,imageUrl:b.data.image_url,displayDomain:b.data.display_domain?b.data.display_domain:null,showLinkIcon:!!b.data.show_link_icon,Zo:b.data.button_icon_url?b.data.button_icon_url:null,title:b.data.title,customMessage:b.data.custom_message?b.data.custom_message:null,url:b0({pause_on_navigation:b.data.pause_on_navigation,
target:b.data.target||"new",value:b.data.url}),Pd:f,yA:b.data.signin_title?b.data.signin_title:null,xA:b.data.signin_message?b.data.signin_message:null,offers:c};y1(a,d);break;case "simple":b.data.signin_url&&(f=b0({target:"current",value:b.data.signin_url}));d={id:b.id,bb:b.bb,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||
!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):null,de:e.icon?g.Ks(e.icon):null,imageUrl:b.data.image_url,displayDomain:b.data.display_domain?b.data.display_domain:null,showLinkIcon:!!b.data.show_link_icon,Zo:b.data.button_icon_url?b.data.button_icon_url:null,title:b.data.title,customMessage:b.data.custom_message?b.data.custom_message:null,url:b0({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url}),Pd:f,yA:b.data.signin_title?b.data.signin_title:
null,xA:b.data.signin_message?b.data.signin_message:null};y1(a,d);break;case "video":d={id:b.id,bb:b.bb,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):null,de:e.icon?g.Ks(e.icon):null,Zk:b.data.image_url,videoDuration:b.data.video_duration||null,customMessage:b.data.custom_message?
b.data.custom_message:null,title:b.data.title,metaInfo:b.data.meta_info,isLiveNow:!!b.data.is_live_now,url:b0({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url})},y1(a,d)}}},epa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){v1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){w1(a)});
var c=b.data.headerText;g.be(a.xa,c);a.O&&a.O.setAttribute("title",c);b.data.eventId&&(a.R=b.data.eventId);a.fa=g.Ks(b.data.trackingParams);a.P=g.Ks(b.data.closeTrackingParams);a.H=g.Ks(b.data.iconTrackingParams)},A1=function(a,b){var c=fpa(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Fb.id),g.Xd(c.jp),g.db(a.l,c),a.Ll(),z1(a))},v1=function(a,b,c,d){if(!a.u){a.ua.show();
a.Z=new g.M(function(){g.J(a.context.Y.getRootNode(),"ytp-iv-drawer-open")},0);
a.Z.start();a.aa=g.Nr(a.o,"mousewheel",(0,g.x)(a.gF,a));a.u=!0;a.X=(0,g.H)();d1(a.context.logger,a.R,7,void 0,d&&d.Fb?d.Fb.bb:void 0);var e=g.at();e&&a.fa&&a.P&&IZ(e,[a.fa,a.P]);var f={TRIGGER_TYPE:b};(0,g.z)(a.l,function(k){k.Tw||(k.Tw=!0,a1(a.context.logger,k.Fb.bb,k.Fb.qd.XD,f));e&&IZ(e,[k.Fb.rf])});
sZ(a.i);c&&(a.C=new g.M(function(){a.da=a.O;a.ma.focus()},330),a.C.start())}},w1=function(a){a.u&&(a.ua.hide(),g.Or(a.aa),a.aa=null,g.Tn(a.context.Y.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,sZ(a.i),a.C&&a.C.stop(),a.C=new g.M(function(){a.da&&(a.da.focus(),a.da=null)},330),a.C.start())},gpa=function(a){var b=g.Hd("iv-drawer-close-button",a.A);
a.context.g.ca(b,"click",a.wC,a);a.context.g.ca(a.o,"touchend",function(){a.M.start()});
a.context.g.ca(a.o,"scroll",a.HC,a);a.context.i.subscribe("onHideControls",function(){a.W=!0});
a.context.i.subscribe("onShowControls",function(){a.W=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.W=g.Rn(a.i.getRootNode(),"ytp-autohide")});
a.I.push(g.Pp("iv-button-shown",a.qE,a));a.I.push(g.Pp("iv-button-hidden",a.pE,a));a.I.push(g.Pp("iv-teaser-shown",a.tE,a));a.I.push(g.Pp("iv-teaser-hidden",a.sE,a));a.I.push(g.Pp("iv-teaser-clicked",a.rE,a))},y1=function(a,b){a.va||(g.Sn(a.ga(),["html5-stop-propagation",
"iv-drawer-manager"]),g.kK(a.i,a.A,5),gpa(a),a.O=g.Hd("ytp-cards-button",a.i.getRootNode()),a.ma=g.Hd("iv-drawer-close-button",a.A),a.va=!0);A1(a,b.id);var c=hpa(a,b);if(c){var d={Fb:b,jp:c.element,Tw:!1},e=ipa(a,d);g.lb(a.l,e,0,d);c.g(a.o,e);a.Ll();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Sa(a.tM,d)):(c=1E3*a.context.Y.getCurrentTime(),5E3>c&&c>b.startMs&&a.jA(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Sa(a.jA,d)),z1(a))}},hpa=function(a,b){switch(b.type){case "simple":var c=
a.D,d=b.displayDomain?{B:"div",
G:"iv-card-image-text",T:b.displayDomain}:"",e=n1(c,b),f=["iv-card"];b.Pd&&f.push("iv-card-unavailable");d=[{B:"a",G:"iv-click-target",L:{href:c0(b.url)},J:[i1(b.imageUrl,d),{B:"div",G:"iv-card-content",J:[g1(c,"h2",void 0,b.title),e]}]}];b.Pd&&d.push({B:"div",V:["iv-card-sign-in"],J:[g1(c,"h2",void 0,b.yA||""),{B:"p",T:b.xA},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:c0(b.Pd)},J:[g1(c,"span","iv-button-content","\u041f\u0440\u0438\u0458\u0430\u0432\u0438 \u043c\u0435")]}]});f=new g.W({B:"div",
V:f,J:d});k1(c,f,b,void 0,void 0);return f;case "collaborator":return c=a.D,f={B:"div",V:["iv-card","iv-card-channel"],J:[{B:"a",V:["iv-click-target"],L:{href:c0(b.url),"data-ytid":b.channelId},J:[i1(b.bM),{B:"div",G:"iv-card-content",J:[m1(c,b),{B:"h2",G:"iv-card-primary-link",T:b.title},j1(c,b)]}]}]},f=new g.W(f),k1(c,f,b),f;case "episode":return l1(a.D,b,"iv-card-episode");case "movie":return l1(a.D,b,"iv-card-movie");case "playlist":return c=a.D,f={B:"div",V:["iv-card","iv-card-playlist"],J:[{B:"a",
G:"iv-click-target",L:{href:c0(b.url)},J:[i1(b.Zk,{B:"div",G:"iv-card-image-overlay",J:[{B:"span",G:"iv-card-playlist-video-count",T:b.playlistVideoCount.toString()}]}),{B:"div",G:"iv-card-content",J:[m1(c,b),g1(c,"h2","iv-card-primary-link",b.title),j1(c,b)]}]}]},f=new g.W(f),k1(c,f,b),f;case "poll":return Zoa(a.D,b);case "productListing":c=a.D;e=0!=b.offers.length;f=["iv-card"];d="";var k=n1(c,b);e&&(f.push("iv-card-product-listing"),d="iv-card-primary-link",e=b.offers[0],k=[],e.price&&k.push({B:"div",
G:"iv-card-offer-price",T:e.price}),e.merchant&&k.push({B:"div",G:"iv-card-offer-merchant",T:e.merchant}),k={B:"div",J:k});f={B:"div",V:f,L:{tabindex:"0"},J:[{B:"a",V:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:c0(b.url),"aria-hidden":"true",tabindex:"-1"}},{B:"div",G:"iv-card-content",J:[b.sponsored?{B:"div",G:"iv-card-sponsored",J:["\u0421\u043f\u043e\u043d\u0437\u043e\u0440\u0438\u0441\u0430\u043d\u043e",{B:"div",G:"iv-ad-info-container",J:[{B:"div",
G:"iv-ad-info",T:"{{adInfo}}"},{B:"div",G:"iv-ad-info-icon-container",J:[{B:"div",G:"iv-ad-info-icon"},{B:"div",G:"iv-ad-info-callout"}]}]}]}:"",{B:"a",G:"iv-click-target",L:{href:c0(b.url)},J:[g1(c,"h2",d,b.title),k]}]}]};f=new g.W(f);d=g.Sd("span");g.be(d,"\u041f\u0440\u0438\u043a\u0430\u0437\u0443\u0458\u0435 \u0432\u0430\u043c \u0441\u0435 \u043e\u0432\u0430\u0458 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434 \u0458\u0435\u0440 \u0441\u043c\u0430\u0442\u0440\u0430\u043c\u043e \u0434\u0430 \u0458\u0435 \u0440\u0435\u043b\u0435\u0432\u0430\u043d\u0442\u0430\u043d \u0437\u0430 \u0432\u0438\u0434\u0435\u043e. Google \u045b\u0435 \u043f\u0440\u0438\u043c\u0430\u0442\u0438 \u043d\u0430\u043a\u043d\u0430\u0434\u0443 \u043e\u0434 \u043f\u0440\u043e\u0434\u0430\u0432\u0446\u0430.");
f.nb(d,"adInfo");k1(c,f,b);return f;case "video":return c=a.D,f=b.isLiveNow?{B:"span",V:["yt-badge","yt-badge-live"],T:"\u0422\u0420\u0415\u041d\u0423\u0422\u041d\u041e \u0423\u0416\u0418\u0412\u041e"}:"",f={B:"div",V:["iv-card","iv-card-video"],J:[{B:"a",G:"iv-click-target",L:{href:c0(b.url)},J:[i1(b.Zk,b.videoDuration?{B:"span",G:"iv-card-video-duration",T:b.videoDuration}:""),{B:"div",G:"iv-card-content",J:[m1(c,b),g1(c,"h2","iv-card-primary-link",b.title),j1(c,b),f]}]}]},f=new g.W(f),k1(c,f,b),
f}return null},ipa=function(a,b){if(0==a.l.length)return 0;
var c=g.Za(a.l,function(d){return b.Fb.startMs>d.Fb.startMs||b.Fb.startMs==d.Fb.startMs&&b.Fb.timestamp>=d.Fb.timestamp?!0:!1});
return-1==c?0:c+1},jpa=function(a){return a.g?"productListing"==a.g.Fb.type:(0,g.jj)(a.l,function(b){return"productListing"==b.Fb.type})},z1=function(a){g.K(a.i.getRootNode(),"ytp-cards-shopping-active",jpa(a))},B1=function(a,b){if(a.F.Da()){var c=new DZ([0,
a.o.scrollTop],[0,b.jp.offsetTop],600,Una);a.context.l.ca(c,"animate",function(d){a.o.scrollTop=d.y});
a.context.l.ca(c,"finish",function(d){a.o.scrollTop=d.y});
c.play()}else g.NC(a.F,!0),a.o.scrollTop=b.jp.offsetTop,g.NC(a.F,!1)},C1=function(a){return a.g&&a.g.Fb?a.g.Fb:a.l[0]&&a.l[0].Fb?a.l[0].Fb:null},fpa=function(a,b){return g.Ya(a.l,function(c){return c.Fb.id==b})},D1=function(a,b,c){u1.call(this,a,b);
this.annotation=c;this.isActive=!1},kpa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},E1=function(a,b,c){D1.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.C=this.A=null},F1=function(a,b,c){D1.call(this,a,b,c);
this.F=this.u=this.H=!1;this.C=5E3;this.o=null;this.D=g.Rd("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.M(function(){this.g.setAttribute("aria-hidden",!0);g.Th(this.l,!1);g.Th(this.i,!0)},700,this);
g.G(this,this.A)},lpa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.C=b.collapse_delay_ms||a.C;var d=["iv-promo","iv-promo-inactive"];a.ga().setAttribute("aria-hidden",!0);a.ga().setAttribute("aria-label","\u041f\u0440\u043e\u043c\u043e\u0446\u0438\u0458\u0430");a.ga().tabIndex=0;var e=a.annotation.Jb(),f=b.image_url;if(f){var k=g.Rd("DIV",["iv-promo-img","iv-click-target"]);f=g.Rd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?
(f=g.Rd("SPAN","iv-promo-video-duration",b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.Rd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Li(k,e,a.annotation.id,b.session_data,a.annotation.bb,void 0,c)}e?(f=g.Rd("A","iv-promo-txt"),g.Uc(f,c0(e)),a.g=f):a.g=g.Rd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_1));var m=g.Rd("P",null,g.Rd("SPAN","iv-promo-link",b.text_line_2));
if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.Q(a.context.wb.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Rd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Rd("BUTTON",["iv-button","iv-promo-button"],g.Rd("SPAN","iv-button-content",f));var p=g.Rd("DIV","iv-promo-button-container");p.appendChild(f);e&&a.Li(a.ga(),e,a.annotation.id,b.session_data,a.annotation.bb,void 0,c)}g.J(a.g,"iv-click-target");e&&a.Li(a.g,e,a.annotation.id,
b.session_data,a.annotation.bb,void 0,c);break;case "playlist":case "video":l=g.Rd("P",null,g.Rd("SPAN",null,b.text_line_1)),m=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Rd("SPAN",["yt-badge","iv-promo-badge-live"],"\u0422\u0420\u0415\u041d\u0423\u0422\u041d\u041e \u0423\u0416\u0418\u0412\u041e")),g.J(a.g,"iv-click-target"),e&&a.Li(a.g,e,a.annotation.id,b.session_data,a.annotation.bb,void 0,c),d.push("iv-promo-video")}l&&a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);
p&&a.D.appendChild(p);c=g.Rd("DIV","iv-promo-actions");a.i=g.Rd("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="\u041f\u0440\u043e\u0448\u0438\u0440\u0438";a.context.g.ca(a.i,"click",g.Sa(a.fq,5E3),a);c.appendChild(a.i);g.Th(a.i,!1);a.context.g.ca(a.ga(),"mouseover",a.zD,a);a.context.g.ca(a.ga(),"mouseout",a.yD,a);a.context.g.ca(a.ga(),"touchend",g.Sa(a.fq,5E3),a);a.l=g.Rd("BUTTON",["iv-promo-close","ytp-button"]);a.l.title="\u0417\u0430\u0442\u0432\u043e\u0440\u0438";a.context.g.ca(a.l,"click",
"cta"==a.annotation.style&&b.text_line_3?a.rD:a.qD,a);c.appendChild(a.l);g.Sn(a.ga(),d);k&&(a.ga().appendChild(k),n&&k.appendChild(n));a.ga().appendChild(a.D);a.ga().appendChild(c)},G1=function(a){a.u||a.F||a.o||(g.J(a.ga(),"iv-promo-collapsed"),a.u=!0,a.A.start())},H1=function(a){a.A.stop();
a.u&&(g.Un(a.ga(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.Th(a.i,!1),g.Th(a.l,!0))},J1=function(a,b){a.o||(a.o=g.Gg(function(){I1(this);
G1(this)},b,a))},I1=function(a){a.o&&(g.v.clearTimeout(a.o),a.o=null)},K1=function(a){g.yK.call(this,a);
this.I=!1;this.H=0;this.i={};this.P={};this.D=new Uoa(a);this.A=new g.vs(this);g.G(this,this.A);this.C=this.l=null;this.A.K(this.player,"onVideoAreaChange",(0,g.x)(this.N,this,"onVideoAreaChange"));this.A.K(this.player,"onHideControls",(0,g.x)(this.N,this,"onHideControls"));this.A.K(this.player,"onShowControls",(0,g.x)(this.N,this,"onShowControls"));this.A.K(this.player,"resize",(0,g.x)(this.N,this,"resize"));this.A.K(this.player,"presentingplayerstatechange",(0,g.x)(this.N,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.dJ,this);this.subscribe("onShowControls",this.XK,this);this.subscribe("presentingplayerstatechange",this.hK,this);this.subscribe("resize",this.wn,this);this.subscribe("G",this.OE,this);this.subscribe("F",this.Cg,this);this.subscribe("D",this.aI,this);this.subscribe("E",this.DI,this);g.X(this.player).I.subscribe("vast_info_card_add",this.hz,this);this.R=new g.vs(this);g.G(this,this.R);this.R.K(this.player,g.ND("annotations_module"),this.ME);this.R.K(this.player,
"crx_annotations_module",this.NE);this.O=g.Rd("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.W=g.Rd("DIV","video-custom-annotations");this.u=new g.W({B:"div",V:["ytp-player-content","ytp-iv-player-content"]});g.G(this,this.u);g.kK(this.player,this.u.element,4);this.u.hide();this.o=new g.W({B:"div",V:["ytp-iv-video-content"]});g.G(this,this.o);g.Ud(this.o.element,g.Rd("DIV","video-annotations",this.O,this.W));this.F=this.g=null;this.M=[];mpa(this)&&this.load();var b=g.Sd("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},L1=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},mpa=function(a){var b=g.X(a.player);
a=a.player.getVideoData();return 1==(b.Xf||a.Xf)&&!a.gB||null!==b.I.get(a.videoId)},M1=function(a,b,c){a.I=!0;
a.C=g.Fq(b,c)},N1=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(N1(a,e))}return c},O1=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},opa=function(a,b){var c=npa(a,b);
if(!c&&"marker"!=b.type)return null;u0(b,function(e){e=(0,g.x)(this.vL,this,b.id,e);this.subscribe("ivTrigger:"+b.id,e)},a);
var d=new U0(a.ua,b,c);g.G(d,c);return d},ppa=function(a,b){var c=g.Rd("DIV",["annotation",
"annotation-type-custom"]);g.Th(c,!1);var d=null;switch(b.type){case "branding":if(g.X(a.player).cj)break;a.u.element.appendChild(c);d=new E1(c,P1(a),b);break;case "promotion":g.kK(a.player,c,4),d=new F1(c,P1(a),b)}d&&d.Vn();return d},qpa=function(a){var b=a.player.getVideoData();
if(b.Fd){var c=g.X(a.player),d=c.I.get(b.videoId);if(d){var e={format:"XML",Dc:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.Dc.gaming="1");e.Zc=(0,g.x)(function(f,k,l){O1(this,f,k)||(f=g.zq(l)&&l.responseXML?l.responseXML:null)&&Q1(this,f)},a,a.H,b.videoId);
g.cq()&&(e.Zc=R1(a,e.Zc));e.tb={ic_only:"1"};S1(e,d);a.I=!0;g.Fq(b.Fd,e)}}},S1=function(a,b){a.method="POST";
a.tb=a.tb||{};b.Ql&&(a.tb.ic_coll=b.Ql);b.Rl&&(a.tb.ic_xml=b.Rl);b.Us&&(a.tb.ic_track=b.Us)},T1=function(a){var b=new g.W({B:"div"});
g.Th(b.element,!1);var c=new x1(a.player,b.element,P1(a));g.G(c,b);b.g(a.u.element);c.Vn();return c},P1=function(a){if(!a.F){var b=new HZ(a);
g.G(a,b);var c=new g.an(a);g.G(a,c);a.F=new Xoa(b,c,g.X(a.player),a.player.getVideoData(),a.D,a.player,a.ua)}return a.F},Q1=function(a,b){var c=!1;
rpa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=N1(a,d[e]),k=null;try{k=Foa(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=ppa(a,k))g.G(a,f),a.P[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=T1(a),g.G(a,a.g)),"card"==k.type?dpa(a.g,k):epa(a.g,k),c=!0;else if(f=opa(a,k))g.G(a,f),a.i[k.id]=f}}c&&(sZ(a.player),a.wn());g.Lb(a.i,function(l){if(l.view){var m=l.annotation;(l=l.view)&&m.segment&&m.segment.i&&
(m=this.i[m.segment.i])&&(l.O=m.annotation)}},a)},spa=function(a,b){var c=!1;
a.g||(a.g=T1(a),g.G(a,a.g));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())c=!0;c&&(sZ(a.player),a.wn())},rpa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.at();
if(b){var c=g.$s();c&&g.Ms(b,c,[g.Ks(a)])}}},tpa=function(a,b,c,d){d?U1(a,b,c):V1(a,b,c)},V1=function(a,b,c){if(b=a.i[b])W0(b),c&&c.i?(a=(0,g.x)(a.uw,a,b),b.g=new g.M(a,2E3),b.g.start()):a.uw(b)},U1=function(a,b,c){if(b=a.i[b])W0(b),c&&c.o?(a=(0,g.x)(a.uA,a,b),b.g=new g.M(a,2E3),b.g.start()):a.uA(b)},W1=function(a,b){var c=a.player.getVideoData();
if(!c.Gl)return!1;var d=c0(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!r1(d))return!1;d=g.mq(d);return d.list||d.p?!1:(d=s1(b))?c.videoId==d?!0:"new"!=b.target&&g.X(a.player).i?!0:!1:!1},npa=function(a,b){if(upa(b)){var c=b.o||s0(b,function(d){return"click"==d||"rollOut"==d||"rollOut"==d});
return new N0(b,(0,g.x)(a.O.appendChild,a.O),a.player,a.ua,c)}return null},upa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in r0)if(a.style==r0[b])return!0;return!1},X1=function(a,b,c,d){a.N(y0(b,d),c,d)},R1=function(a,b){return(0,g.x)(function(){if(!this.ea()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Sa.apply(window,c);this.M.push(g.aq(b))}},a)};
g.RJ.prototype.Hi=g.da(14,function(a,b){var c=g.SJ(this).l;c&&c.Hi(a,b)});
g.ho.prototype.cq=g.da(0,function(){this.i=this.M.createElement("DIV")});
var Nna=/[^\d]+$/,Ona={cm:1,"in":1,mm:1,pc:1,pt:1},Pna={em:1,ex:1},xZ={},yZ=null;g.y(CZ,g.sf);g.y(DZ,g.Wn);g.h=DZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;zZ(this);this.startTime=a=(0,g.H)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Vd("play");-1==this.g&&this.Vd("resume");this.g=1;var b=g.Ra(this);b in xZ||(xZ[b]=this);AZ();BZ(this,a);return!0};
g.h.stop=function(a){zZ(this);this.g=0;a&&(this.progress=1);EZ(this,this.progress);this.Vd("stop");this.l()};
g.h.pause=function(){1==this.g&&(zZ(this),this.g=-1,this.Vd("pause"))};
g.h.U=function(){0==this.g||this.stop(!1);this.Vd("destroy");DZ.Xa.U.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Mr=function(){this.Vd("animate")};
g.h.Vd=function(a){this.dispatchEvent(new CZ(a,this))};
g.y(FZ,DZ);FZ.prototype.u=g.Ja;FZ.prototype.Mr=function(){this.u();FZ.Xa.Mr.call(this)};
FZ.prototype.l=function(){this.u();FZ.Xa.l.call(this)};
FZ.prototype.o=function(){this.u();FZ.Xa.o.call(this)};
g.y(GZ,FZ);GZ.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.t(HZ,g.D);HZ.prototype.ca=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.Nr(a,b,c);this.g.push(a);return a};
HZ.prototype.Om=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.Xr(a,b,c);this.g.push(a);return a};
HZ.prototype.Ka=function(a){g.Or(a);g.db(this.g,a)};
HZ.prototype.U=function(){g.Or(this.g);this.g.length=0;g.D.prototype.U.call(this)};g.y(KZ,g.Sf);g.h=KZ.prototype;g.h.Wp=null;g.h.Rj=null;g.h.ga=function(){return this.Rj};
g.h.addEventListener=function(a,b,c,d){g.Cf(this.Rj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Mf(this.Rj,a,b,c,d)};
g.h.U=function(){KZ.Xa.U.call(this);var a=this.Rj;if(a)if(g.vf(a))a.me&&g.zf(a.me);else if(a=g.Ff(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.Nf(d[e])&&++b}};g.y(PZ,KZ);PZ.prototype.fill=null;g.y(RZ,KZ);SZ.prototype.Ee=null;SZ.prototype.xd=null;SZ.prototype.Vk=!0;var Xna=[2,2,6,6,0];g.h=SZ.prototype;g.h.clear=function(){this.Ta.length=0;this.Ca.length=0;this.Sd.length=0;delete this.Ee;delete this.xd;delete this.Vk;return this};
g.h.moveTo=function(a,b){0==g.Wa(this.Ta)?this.Sd.length-=2:(this.Ta.push(0),this.Ca.push(1));this.Sd.push(a,b);this.xd=this.Ee=[a,b];return this};
g.h.Zb=function(a){var b=g.Wa(this.Ta);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Ta.push(1),this.Ca.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Sd.push(c,d)}this.Ca[this.Ca.length-1]+=b/2;this.xd=[c,d]};
g.h.close=function(){var a=g.Wa(this.Ta);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Ta.push(4),this.Ca.push(1),this.xd=this.Ee);return this};
g.h.clone=function(){var a=new this.constructor;a.Ta=this.Ta.concat();a.Ca=this.Ca.concat();a.Sd=this.Sd.concat();a.Ee=this.Ee&&this.Ee.concat();a.xd=this.xd&&this.xd.concat();a.Vk=this.Vk;return a};
g.h.transform=function(a){if(!this.Vk)throw Error("Non-simple path");a.transform(this.Sd,0,this.Sd,0,this.Sd.length/2);this.Ee&&a.transform(this.Ee,0,this.Ee,0,1);this.xd&&this.Ee!=this.xd&&a.transform(this.xd,0,this.xd,0,1);return this};
g.h.isEmpty=function(){return 0==this.Ta.length};g.y(A_,PZ);g.y(C_,g.ho);C_.prototype.o=null;C_.prototype.Gj=function(){return this.hh?g.Sh(this.ga()):g.Ha(this.width)&&g.Ha(this.height)?new g.wd(this.width,this.height):null};
C_.prototype.resume=function(){};g.y(MZ,QZ);g.y(LZ,QZ);g.y(D_,RZ);D_.prototype.clear=function(){g.Vd(this.ga())};
D_.prototype.setSize=function(a,b){var c=this.ga(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.y(E_,A_);var H_;g.y(F_,C_);var $na=0;g.h=F_.prototype;g.h.cq=function(){var a=NZ(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=NZ(this,"g");this.C=NZ(this,"defs");this.o=new D_(b,this);a.appendChild(this.C);a.appendChild(b);this.i=a;this.l&&(this.ga().setAttribute("preserveAspectRatio","none"),this.R?this.WA():this.ga().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.I:"")))};
g.h.WA=function(){if(this.hh){var a=this.Gj();0==a.width?this.ga().style.visibility="hidden":(this.ga().style.visibility="",this.o.ga().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.I+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.Rh(this.ga(),a,b)};
g.h.Gj=function(){if(!g.Bh)return this.hh?g.Sh(this.ga()):F_.Xa.Gj.call(this);var a=this.width,b=this.height,c=g.Fa(a)&&-1!=a.indexOf("%"),d=g.Fa(b)&&-1!=b.indexOf("%");if(!this.hh&&(c||d))return null;if(c){var e=this.ga().parentNode;var f=g.Sh(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ga().parentNode,f=f||g.Sh(e),b=parseFloat(b)*f.height/100);return new g.wd(a,b)};
g.h.clear=function(){this.o.clear();g.Vd(this.C);this.g={}};
g.h.vj=function(){F_.Xa.vj.call(this);this.R&&this.P.Ka(aoa(),"tick",this.WA)};
g.h.U=function(){delete this.g;delete this.C;delete this.o;this.P.dispose();delete this.P;F_.Xa.U.call(this)};g.t(J_,g.yK);g.h=J_.prototype;
g.h.load=function(){g.yK.prototype.load.call(this);if(!L_(g.X(this.player).playerStyle)){var a=g.IB(this.player.getVideoData());if(a)a=I_(a,K_(this)),M_(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Zc:(0,g.x)(this.UI,this,a),Dc:{v:a},withCredentials:!0};"gaming"==g.X(this.player).playerStyle&&(a.Dc.gaming="1");this.P&&(a.Dc.ptype="embedded");var c=this.player.getVideoData().qv;c&&(a.tb={ad_tracking:c});if(b=g.HB(b))if(b=g.Dc(b),b=g.Ac(b))this.o=
g.Fq(b,a)}}};
g.h.unload=function(){M_(this,null);this.o&&(this.o.abort(),this.o=null);g.yK.prototype.unload.call(this)};
g.h.xc=function(a,b){if(!L_(g.X(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=I_(b,"new");M_(this,c);return!0}return null};
g.h.getOptions=function(){return L_(g.X(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.UI=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=I_(c,K_(this)))}M_(this,c)};
g.h.Wa=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Y1.length;f++){var k=Math.abs(b.width-Y1[f]);if(-1==e||d>=k)e=f,d=k}d=Z1[e];this.l&&g.zh(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.C[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Rh(e.element,Math.round(k.width*a.width),f);g.Hh(e.element,m,n);g.Un(e.element,vpa);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Un(e.element,Z1);g.J(e.element,d);(e=g.Fd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.zh(e,"height",f+"px")}}}}};
g.h.QE=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.$J(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(R_(this,this.i.impressionUrls),(a=g.at())&&this.i.visualElement&&g.Ns(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.C[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");R_(this,c.impressionUrls);
(b=g.at())&&g.Ns(b,c.visualElement);g.X(this.player).qb&&this.player.la("endscreenelementshown",a)}};
g.h.RE=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.Tn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Tn(b,"ytp-ce-shown");g.X(this.player).qb&&this.player.la("endscreenelementhidden",a)}};
g.h.KL=function(a){var b=this;a.target===window&&(new g.M(function(){for(var c in b.g)g.Un(b.g[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.Jy=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Rn(c,"ytp-ce-element");){g.Rn(c,"subscribe-label")&&S_(this,a);if(g.Rn(c,"ytp-ce-channel-subscribe"))return;c=g.$d(c)}if(!c||g.Rn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.Rr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.Zn?(S_(this,a),this.dA(),this.player.pauseVideo(),c=g.Dc(O_(this,a.targetUrl)),c=g.Ac(c),g.pL(c,void 0,a.Xb)):(c=this.player.getVideoData().Nb,
c=(0,g.x)(this.AM,this,c,O_(this,a.targetUrl),a.Xb),c=(0,g.x)(this.dA,this,c),S_(this,a,c))}}};
g.h.AM=function(a,b,c){var d=g.mq(b);a&&d&&(d.v||d.list)?g.SX(this.player.app,d.v,c,d.list,!1,void 0):g.oL(b,c)};
g.h.Xq=function(a,b){g.Rn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):g.X(this.player).g?(new g.M(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),R_(this,b.VD),Q_(this,b.id,!0))};
g.h.Rr=function(a,b){g.Tn(a.element,"ytp-ce-element-hover");g.Tn(a.element,"ytp-ce-force-expand");Q_(this,b.id,!1)};
g.h.dA=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var Y1=[346,426,470,506,570,640,853,1280,1920],Z1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),vpa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var loa={eO:"current",lP:"new"};var noa={CLOSE:"close",pP:"openUrl",YB:"subscribe"},ooa={ZN:"click",CLOSE:"close",HO:"hidden",PP:"rollOut",UB:"rollOver",VB:"shown"};var qoa={uQ:"xx",vQ:"xy",wQ:"yx",xQ:"yy"};g.t(m0,f0);var voa={tB:"anchored",LP:"rect",SP:"shapeless"};var zoa={CLOSED:"closed",yP:"playerControlShow",UB:"rollOver",VB:"shown"};q0.prototype.Jb=function(){var a=Hoa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
q0.prototype.showLinkIcon=function(){return s0(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var r0={tB:"anchored",wB:"branding",CHANNEL:"channel",dO:"cta",JO:"highlightText",XO:"label",PLAYLIST:"playlist",BP:"popup",WP:"speech",YB:"subscribe",gQ:"title",VIDEO:"video",qQ:"website"},Doa={wB:"branding",QN:"card",kO:"drawer",IO:"highlight",fP:"marker",GP:"promotion",TEXT:"text",sQ:"widget"},Eoa={oQ:"video_relative",zP:"player_relative"};z0.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.Pb(this.g,function(e){return e});
this.l!=a&&(this.l=a,this.i.N(this.u,a,d))};A0.prototype.ga=function(){return this.u};
A0.prototype.l=function(){};var E0={bevel:1,dropshadow:2};g.t(J0,A0);
J0.prototype.l=function(a,b){var c=w0(a);if(c){var d=j0(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=v0(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.qh(h0(b,i0(e,new g.nh(e.D,e.F,e.Vi,e.l),b.g))),k=d.clone();c=new g.nh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.g;k=H0(k,c.effects);l=B0(this,k.width,k.height);m=G0(c,k.width,k.height,this.g);
d=new g.nh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.ud(f.x-k.left,f.y-k.top);this.o=17*e0(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.g;var p=this.g&&t0(a),r=p?f.borderWidth+1:f.borderWidth;p=(f=r?new B_(r,p?f.i:f.borderColor):null)?f.g/2:0;r=Poa(d,n);var u=this.A(d,e,n,r),A=n.x;n=n.y;var C=d.width,E=d.height,F=d.left;d=d.top;var L=new SZ;L.moveTo(F+e+p,d+p);"t"==r&&(L.Zb(u.start,d+p),L.Zb(A,n),L.Zb(u.end,d+p));L.Zb(F+C-e-p,d+p);m_(L,e,e,-90);"r"==r&&(L.Zb(F+C-p,u.start),L.Zb(A,n),L.Zb(F+
C-p,u.end));L.Zb(F+C-p,d+E-e-p);m_(L,e,e,0);"b"==r&&(L.Zb(u.end,d+E-p),L.Zb(A,n),L.Zb(u.start,d+E-p));L.Zb(F+e+p,d+E-p);m_(L,e,e,90);"l"==r&&(L.Zb(F+p,u.end),L.Zb(A,n),L.Zb(F+p,u.start));L.Zb(F+p,d+e+p);m_(L,e,e,180);L.close();G_(l,L,f,m);if(m=this.ga())g.J(m,"annotation-shape"),g.J(m,"annotation-speech-shape"),g.Hh(m,k.left,k.top),g.Rh(m,k.width,k.height),I0(l,m,c.effects)}}}};
J0.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=g.qd(k-f/2,l+b,l+m-f-b);return new g.Bi(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Bi(0,0)};g.t(K0,A0);K0.prototype.l=function(a,b){var c=w0(a);if(c){var d=j0(c,b);if(!(0>=d.width||0>=d.height)){var e=a.g;c=H0(d,e.effects);var f=B0(this,c.width,c.height),k=new B_(!e.l&&this.g?1:e.l,e.bgColor),l=new LZ("#000",0);d=F0(new g.nh(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);G_(f,d,k,l);f=this.ga();g.J(f,"annotation-shape");e=e.g;uZ(f,this.g?Math.max(e,.9):e);g.Hh(f,c.left,c.top);g.Rh(f,c.width,c.height)}}};g.t(L0,A0);
L0.prototype.l=function(a,b){var c=w0(a);if(c){var d=j0(c,b);if(!(0>=d.width||0>=d.height)){c=a.g;var e=H0(d,c.effects),f=B0(this,e.width,e.height),k=new g.nh(0,0,d.width,d.height);d=G0(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.g;var n=this.g&&t0(a),p=n?m.borderWidth+1:m.borderWidth;m=p?new B_(p,n?m.i:m.borderColor):null;k=F0(k,l,m?m.g/2+1:0);G_(f,k,m,d);if(k=this.ga())g.J(k,"annotation-shape"),g.J(k,"annotation-popup-shape"),g.Hh(k,e.left,e.top),g.Rh(k,e.width,e.height),I0(f,k,c.effects)}}};g.t(M0,J0);M0.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=k<=l+m/2?Math.max(l+m/4-f/2,l+b):Math.min(l+3*m/4-f/2,l+m-f-b);return new g.Bi(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Bi(0,0)};g.t(N0,g.D);g.h=N0.prototype;g.h.vx=function(){this.F||(this.o&&g.Th(this.o,!0),this.u&&g.Th(this.u,!0),this.l&&(this.l.g=!0,uZ(this.i,S0(this)?1:0),this.l.l(this.g,P0(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.ba.Om(g.XJ(this.A),"mouseleave",function(a){this.qn.stop();this.Cg(a)}))};
g.h.Cg=function(){this.F&&(this.M?this.D.start():this.ww(),this.l&&(this.l.g=!1,uZ(this.i,S0(this)?1:0),this.l.l(this.g,P0(this))),this.F=!1,this.H&&(this.ba.Ka(this.H),this.H=null))};
g.h.ww=function(){this.o&&g.Th(this.o,!1);this.u&&g.Th(this.u,!1)};
g.h.IF=function(a){this.aa=a;this.qn.Pj()};
g.h.xD=function(){var a=this.aa,b=new g.ud(a.clientX,a.clientY),c=g.Lh(this.A.getRootNode()),d=T0(c,this.P);c=(this.u&&vZ(this.u)||this.o&&vZ(this.o))&&T0(c,this.M);d&&d.contains(b)||c&&c.contains(b)?this.vx(a):this.Cg(a)};
g.h.show=function(){var a=this.g.g;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=P0(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new K0:"popup"==this.g.style?d=new L0:"anchored"==this.g.style?d=new J0:"speech"==this.g.style&&(d=new M0);d&&(d.l(this.g,c),this.l=d,c=d.ga())&&(g.Th(c,!1),g.J(c,"annotation-type-"+this.g.type.toLowerCase()),this.R(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.Rd("DIV",c);g.Th(this.i,!1);this.g.l&&(this.C=g.Rd("DIV","inner-text"),"label"==this.g.style&&(g.J(this.C,"player-label-text"),this.C.style.backgroundColor=this.g.g.bgColor),g.be(this.C,this.g.l),this.i.appendChild(this.C));g.Fp(this.i,"annotation_id",this.g.id);this.R(this.i);Qoa(this,this.i);if(t0(this.g)&&this.g.showLinkIcon()){if(d=this.g.Jb())c=this.i,d=new g.Nm(c0(d)),c.title=d.g+d.i;this.u=g.Rd("SPAN","annotation-link-icon");g.Th(this.u,
!1);this.i.appendChild(this.u)}Roa(this);t0(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=o0(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ga()&&(this.l.ga().style.zIndex=a)}g.Th(this.i,!0);uZ(this.i,S0(this)?1:0);R0(this);this.l&&this.l.ga()&&g.Th(this.l.ga(),!0)};
g.h.hide=function(){this.i&&g.Th(this.i,!1);this.l&&this.l.ga()&&g.Th(this.l.ga(),!1);this.I&&(this.ba.Ka(this.I),this.I=null)};g.t(U0,g.D);g.h=U0.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(V0(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.tx,this),this.i.subscribe("onVideoAreaChange",this.iz,this))};
g.h.destroy=function(){if(this.view){V0(this);var a=this.view,b=a.ba;g.Or(b.g);b.g.length=0;a.qn.dispose();a.D.dispose();a.i&&g.Xd(a.i);a.l&&a.l.ga()&&g.Xd(a.l.ga())}W0(this)};
g.h.iz=function(){R0(this.view)};
g.h.tx=function(){R0(this.view)};f1.prototype.l=function(a,b){var c=g.ge(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
f1.prototype.u=function(a,b){var c=g.ge(b.target,null,"iv-card-poll",void 0);if(c)if(a.Pd)g.Hd("iv-card-sign-in-button",c).click();else{var d=parseInt(Rna(b.target),10);if(null==a.he)a.choices[d].count++,a.he=d;else if(a.he!=d){var e=a.choices[a.he];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.he=d}else e=a.choices[a.he],e.count=Math.max(e.count-1,0),a.he=null;h1(a,c);g.Jq(this.g.videoData.Fd,{Dc:{action_poll_vote:1},tb:{poll_id:a.id,index:d,session_token:a.gN}});b1(this.g.logger,a.bb,void 0,
{"link-id":d},a.qd.click,5);(c=g.at())&&a.rf&&g.Os(c,a.rf)}};g.t(u1,g.D);g.h=u1.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.KD(a,b,{id:c});g.G(this,a);a.namespace="annotations_module";d&&qZ(a).subscribe("onEnter",d,this);e&&qZ(a).subscribe("onExit",e,this);g.dK(this.context.Y,[a])};
g.h.Vn=function(){this.context.i.subscribe("resize",this.Ll,this)};
g.h.ga=function(){return this.Ba};
g.h.Li=function(a,b,c,d,e,f,k){this.context.g.ca(a,"click",g.Sa(this.Nm,b,c,d,e,f||[],k||0),this);this.context.g.ca(a,"touchstart",g.Sa(function(){this.jt=!1}),this);
this.context.g.ca(a,"touchmove",g.Sa(function(){this.jt=!0}),this)};
g.h.Nm=function(a,b,c,d,e,f,k){if(this.jt)return!1;k&&(k.stopPropagation(),k.preventDefault());cpa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.X=(0,g.H)()};
g.h.hide=function(){};
g.h.destroy=function(){g.Xd(this.ga())};
g.h.Ll=function(){};g.t(x1,u1);g.h=x1.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.Sh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Ll=function(){var a=this.isAvailable();g.Th(this.ga(),a);g.K(this.context.Y.getRootNode(),"ytp-iv-drawer-enabled",a);sZ(this.i)};
g.h.destroy=function(){this.i.Hi(!1);this.i.getRootNode().removeChild(this.A);g.Qp(this.I);g.Or(this.aa);this.Z&&this.Z.dispose();this.C&&this.C.dispose();u1.prototype.destroy.call(this)};
g.h.gF=function(a){this.M.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.jA=function(a){if(!g.Rn(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.at(),c=this.g?this.g.Fb.de:this.H;b&&c&&JZ(b,[c]);this.g=a;z1(this)}vZ(this.ga())&&(2==this.context.Y.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.Y.getAdState():void 0):(b=isNaN(void 0)?this.context.Y.getPlayerState():void 0,b=1==b||0==b&&0===this.context.Y.getCurrentTime()),b&&a.Fb.teaserDurationMs&&this.i.Hi(!0,{teaserText:a.Fb.teaserText,durationMs:a.Fb.teaserDurationMs}));this.ka.isActive()||
((!this.u||!this.M.isActive()&&this.W)&&B1(this,a),this.ka.start(910+a.Fb.teaserDurationMs))}};
g.h.tM=function(a){this.u||(this.g=a,z1(this),B1(this,a),v1(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.wC=function(){if(this.u){d1(this.context.logger,this.R,4,C1(this).qd.close);var a=g.at();a&&this.P&&g.Os(a,this.P);w1(this)}};
g.h.HC=function(){g.K(this.A,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.qE=function(){var a=g.at(),b=C1(this);b=b?b.de:this.H;a&&b&&IZ(a,[b])};
g.h.pE=function(){var a=g.at(),b=C1(this);b=b?b.de:this.H;a&&b&&JZ(a,[b])};
g.h.tE=function(){var a=C1(this);e1(this.context.logger,8,a.bb,a.qd.HM);var b=g.at();b&&a&&IZ(b,[a.af,a.de])};
g.h.sE=function(){var a=g.at(),b=C1(this);a&&b&&JZ(a,[b.af])};
g.h.rE=function(a){var b=C1(this),c=g.at();this.g?a?(a=this.context.logger,e1(a,9,b.bb,b.qd.Ns),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.af&&g.Os(c,b.af)):(a=this.context.logger,e1(a,12,b.bb,b.qd.Ns),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.de&&g.Os(c,b.de)):(a=this.context.logger,d1(a,this.R,12,b.qd.Ns),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.Os(c,this.H))};g.t(D1,u1);D1.prototype.Vn=function(){u1.prototype.Vn.call(this);kpa(this)};
D1.prototype.show=function(){u1.prototype.show.call(this);var a=g.at(),b=this.annotation.data;a&&b&&(b=b.session_data)&&IZ(a,[g.Ks(b.itct)])};
D1.prototype.hide=function(){u1.prototype.hide.call(this);var a=g.at(),b=this.annotation.data;a&&b&&(b=b.session_data)&&JZ(a,[g.Ks(b.itct)])};g.t(E1,D1);g.h=E1.prototype;g.h.BM=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.Sh(a);this.g||(g.Qh(a,e.width),g.Qh(b,e.width));g.zh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.zh(c,"right","1px");this.o=!0;g.Th(a,!0);this.A=new g.M(function(){g.J(this.ga(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.TD=function(a,b){g.Tn(this.ga(),"iv-branding-active");this.C=new g.M((0,g.x)(function(){g.Th(a,!1);this.g||g.Qh(b,0)},this),250);
this.C.start();this.o=!1};
g.h.show=function(){if(!this.isActive){D1.prototype.show.call(this);if(!this.D){g.J(this.ga(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.Rd("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Th(this.i,!1);var b=g.Rd("DIV","branding-img-container",this.i);this.ga().appendChild(b);var c=g.Rd("DIV","iv-branding-context-name");g.be(c,a.channel_name);var d=g.Rd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.MV(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.Y),this.g.g(d);b=g.Rd("DIV","iv-branding-context-subscribe-caret");c=g.Rd("DIV","branding-context-container-inner",b,c,d);g.Th(c,!1);d=g.Rd("DIV","branding-context-container-outer",c);g.zh(d,"right",this.u+"px");this.ga().appendChild(d);var e=this.annotation.Jb();e&&this.Li(this.i,e,this.annotation.id,a.session_data,
this.annotation.bb);this.l=new g.M(g.Sa(this.TD,c,d),500,this);g.G(this,this.l);this.context.g.ca(this.ga(),"mouseover",(0,g.x)(this.BM,this,c,d,b,a.image_height));this.context.g.ca(this.ga(),"mouseout",(0,g.x)(this.l.start,this.l,void 0));this.D=!0}a1(this.context.logger,this.annotation.bb);g.Th(this.ga(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=tZ(a).width;c=g.Ha(void 0)?void 0:b;g.Hh(a,c);f=new GZ(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,Tna);g.G(this,f);this.context.l.ca(f,
"begin",g.Sa(g.Th,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(D1.prototype.hide.call(this),g.Th(this.ga(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);D1.prototype.destroy.call(this)};g.t(F1,D1);g.h=F1.prototype;g.h.show=function(){this.isActive||(D1.prototype.show.call(this),this.H||(lpa(this),this.H=!0),g.Th(this.ga(),!0),this.annotation&&this.annotation.bb&&a1(this.context.logger,this.annotation.bb),g.Gg(function(){g.Tn(this.ga(),"iv-promo-inactive")},100,this),this.ga().removeAttribute("aria-hidden"),this.isActive=!0,I1(this),H1(this),J1(this,this.C))};
g.h.hide=function(){this.isActive&&(g.J(this.ga(),"iv-promo-inactive"),this.isActive=!1,this.ga().setAttribute("aria-hidden",!0))};
g.h.Nm=function(a,b,c,d,e,f,k){return this.u?!1:D1.prototype.Nm.call(this,a,b,c,d,e,f,k)};
g.h.fq=function(a,b){b.stopPropagation();H1(this);J1(this,a);this.g.focus()};
g.h.zD=function(a){this.F=!0;this.fq(500,a)};
g.h.yD=function(){this.F=!1;G1(this)};
g.h.qD=function(a){a.stopPropagation();this.hide();c1(this.context.logger,this.annotation.bb)};
g.h.rD=function(a){a.stopPropagation();I1(this);this.u=!0;g.J(this.ga(),"iv-promo-collapsed-no-delay");this.A.start();c1(this.context.logger,this.annotation.bb)};
g.h.destroy=function(){this.A.dispose();D1.prototype.destroy.call(this)};g.t(K1,g.yK);g.h=K1.prototype;g.h.xc=function(a,b){if(!L1(g.X(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Vn(b);c&&Q1(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(A1(this.g,b),sZ(this.player)),!0}return null};
g.h.getOptions=function(){return L1(g.X(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.wn=function(){if(this.o){var a=g.XJ(this.player).getVideoContentRect(!0);g.Rh(this.o.element,a.width,a.height);g.Hh(this.o.element,a.left,a.top)}if(this.g){var b=g.bK(this.player);a=this.g;b=b.width;g.K(a.A,"iv-drawer-small",426>=b);g.K(a.A,"iv-drawer-big",1280<=b)}};
g.h.hK=function(a){this.gc(a.state);g.U(a.state,2)&&(this.ud()&&this.De()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Hi(!1))};
g.h.load=function(){g.yK.prototype.load.call(this);this.gc(g.WJ(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.VI,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.cq()&&(c=R1(this,c));c={format:"XML",Zc:c,onError:d,Dc:{}};a.isPharma&&(c.Dc.pharma="1");c.method="POST";c.withCredentials=!0;d=g.X(this.player);"gaming"==d.playerStyle&&(c.Dc.gaming="1");(b=d.I.get(b))&&S1(c,b);b=b&&(b.Rl||b.Ql);if(!a.Fl||b)a.Fd?M1(this,a.Fd,c):(this.l=(0,g.x)(this.PE,this,c),this.player.addEventListener("videodatachange",this.l));g.kK(this.player,this.o.element,4);this.wn();(a=a.Ra&&a.Ra.cards&&a.Ra.cards.cardCollectionRenderer||null)&&spa(this,a)};
g.h.gc=function(a){a=!a.isCued()&&!g.U(a,1024);g.NC(this.u,a);g.NC(this.o,a)};
g.h.PE=function(a){var b=this.player.getVideoData();b.Fd&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),M1(this,b.Fd,a))};
g.h.unload=function(){Voa(this.D);g.gK(this.player,"annotations_module");g.Lb(this.i,function(a){a.destroy()});
g.Lb(this.P,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,sZ(this.player));this.I=!1;this.C&&(this.C.abort(),this.C=null);this.i={};this.P={};this.u.hide();g.yK.prototype.unload.call(this);g.MC(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.VI=function(a,b,c){this.C=null;if(!O1(this,b,a)&&(a=g.zq(c)&&c.responseXML?c.responseXML:null)){Q1(this,a);g.J(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.l,f.visible=!0);b=new g.KD(c,e,f);a.push(b)}}g.dK(this.player,a)}};
g.h.hz=function(a){a==this.player.getVideoData().videoId&&(this.loaded?qpa(this):this.load())};
g.h.ME=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,U1(this,a),a1(this.D,b.bb))};
g.h.NE=function(a){V1(this,a.getId())};
g.h.uw=function(a){a&&(a.hide(),X1(this,"shown",!1,a.annotation.id),this.Zl(a.annotation,"hidden"))};
g.h.uA=function(a){a&&(a.show(),X1(this,"shown",!0,a.annotation.id),this.Zl(a.annotation,"shown"))};
g.h.vL=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;u0(d.annotation,function(f){e=e||f.value});
tpa(this,a,b,e)}};
g.h.aI=function(a){if(a&&a.id){var b=a.Jb();if(b){var c=c0(b);if(c){var d=(0,g.x)(this.Zl,this,a,"click");if("new"==t1(c,b.target)||W1(this,b))d(),d=null;b1(this.D,a.bb,d)}}}};
g.h.Zl=function(a,b){Goa(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!W1(this,c.url))){e=s1(c.url);var f=$oa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=P1(this).Y,g.SX(d.app,e,void 0,void 0,void 0,void 0),f&&P1(this).Y.dc()&&P1(this).Y.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.X(this.player),(d=c0(c.url))?(f=q1(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Sa(apa,e.pageId,e.hc),d=new g.Nm(d),e=e(d.i),d.i=e,d=d.toString())):d=null,d&&
(this.player.pauseVideo(),c=t1(d,c.url.target),e=a.itct,"ei"in g.mq(d)&&(d=g.hh(d,"ei")),g.pL(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.dJ=function(){X1(this,"playerControlShow",!1)};
g.h.XK=function(){X1(this,"playerControlShow",!0)};
g.h.OE=function(a){X1(this,"rollOver",!0,a.id)};
g.h.Cg=function(a){X1(this,"rollOver",!1,a.id)};
g.h.DI=function(a){a&&a.id&&(this.i[a.id].l=!0,V1(this,a.id),c1(this.D,a.bb),this.Zl(a,"close"),X1(this,"closed",!0,a.id))};
g.h.ud=function(){return!!this.g&&this.g.isAvailable()};
g.h.De=function(){this.ud();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ud();this.g&&(a?c?v1(this.g,c,b):v1(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):w1(this.g))};
g.h.Hi=function(a,b){this.player.N(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.U=function(){g.X(this.player).I.unsubscribe("vast_info_card_add",this.hz,this);g.Tn(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.M,b=0,c=a.length;b<c;b++)g.dq(a[b]);this.M.length=0;g.yK.prototype.U.call(this)};g.UU.annotations_module=K1;g.UU.creatorendscreen=J_;})(_yt_player);
