(function(g){var window=this;var E3=function(a,b,c){var d=b.oa();g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.yc(c?c:"mqdefault.jpg");var f=b instanceof g.VA&&b.lengthSeconds?g.BQ(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.OD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.VA?b.sa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.ij||g.hN("\u041f\u043e\u0433\u043b\u0435\u0434\u0430\u0458\u0442\u0435 $TITLE",
{TITLE:b.title}),duration:f,url:b.Mj(),is_live:l,is_list:k,is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.QD&&(d.playlist_length=b.getLength());a.update(d)},F3=function(a,b){g.OC.call(this,{B:"div",
V:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},G3=function(a){g.W.call(this,{B:"div",
V:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{B:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-upnext-top",J:[{B:"span",G:"ytp-upnext-header",T:"\u0421\u043b\u0435\u0434\u0435\u045b\u0435"},{B:"span",G:"ytp-upnext-title",T:"{{title}}"},{B:"span",G:"ytp-upnext-author",T:"{{author}}"}]},{B:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"\u041f\u0443\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0435\u045b\u0438 \u0432\u0438\u0434\u0435\u043e"},
J:[{B:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{B:"circle",G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{B:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{B:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{B:"span",G:"ytp-upnext-bottom",
J:[{B:"span",G:"ytp-upnext-cancel"},{B:"span",G:"ytp-upnext-paused",T:"\u0410\u0443\u0442\u043e\u043f\u043b\u0435\u0458 \u0458\u0435 \u043f\u0430\u0443\u0437\u0438\u0440\u0430\u043d"}]}]});this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.W({B:"button",V:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"\u041e\u0442\u043a\u0430\u0436\u0438 \u0430\u0443\u0442\u043e\u043f\u043b\u0435\u0458"},T:"\u041e\u0442\u043a\u0430\u0436\u0438"});g.G(this,this.A);this.A.ca("click",
this.pI,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.u=null;this.F=new g.M(this.Tl,5E3,this);g.G(this,this.F);this.H=0;this.K(this.i["ytp-upnext-autoplay-icon"],"click",this.cK);this.By();this.K(a,"autonavvisibility",this.By);this.K(a,"mdxnowautoplaying",this.uJ);this.K(a,"mdxautoplaycanceled",this.vJ);this.K(a,"mdxautoplayupnext",this.YA);3==this.l.getPresentingPlayerType()&&(a=(a=g.YJ(g.SJ(this.l)))?a.hD():null)&&this.YA(a)},H3=function(a,b){if(!a.o){g.Sp("a11y-announce",
"\u0421\u043b\u0435\u0434\u0435\u045b\u0435 "+a.u.title);
a.H=g.O();a.o=new g.M((0,g.x)(a.To,a,b),25);a.To(b);var c=b||g.R(g.X(a.l).experiments,"autoplay_time")||1E4;a.l.la("onAutonavCoundownStarted",c)}g.Tn(a.element,"ytp-upnext-autoplay-paused")},J3=function(a){I3(a);
a.H=g.O();a.To();g.J(a.element,"ytp-upnext-autoplay-paused")},I3=function(a){a.o&&(a.o.dispose(),a.o=null)},K3=function(a,b){b=void 0===b?!1:b;
if(g.Q(g.X(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.oa(),a.Tl(),a.C=new Notification("\u0421\u043b\u0435\u0434\u0435\u045b\u0435",{body:c.title,icon:c.yc()}),a.D=a.K(a.C,"click",a.UJ),a.F.start())}I3(a);a.l.nextVideo(!1,b)},L3=function(a){F3.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.W({B:"div",G:"ytp-subscribe-card",J:[{B:"img",G:"ytp-author-image",L:{src:b.Nd}},{B:"div",G:"ytp-subscribe-card-right",J:[{B:"div",G:"ytp-author-name",T:b.author},{B:"div",G:"html5-subscribe-button-container"}]}]});g.G(this,this.l);this.l.g(this.element);this.o=new g.MV("\u041f\u0440\u0430\u0442\u0438",null,"\u041f\u0440\u0435\u043a\u0438\u043d\u0438 \u043f\u0440\u0430\u045b\u0435\u045a\u0435",null,!0,!1,b.Sf,b.subscribed,"trailer-endscreen",null,null,a);g.G(this,
this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},M3=function(a){var b=g.X(a),c=g.Ow||g.Ch?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{B:"a",V:e,L:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{B:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-videowall-still-info",J:[{B:"span",G:"ytp-videowall-still-info-bg",J:[{B:"span",G:"ytp-videowall-still-info-content",L:c,J:[{B:"span",G:"ytp-videowall-still-info-title",T:"{{title}}"},{B:"span",G:"ytp-videowall-still-info-author",
T:"{{author_and_views}}"},{B:"span",G:"ytp-videowall-still-info-live",T:"\u0423\u0436\u0438\u0432\u043e"},{B:"span",G:"ytp-videowall-still-info-duration",T:"{{duration}}"}]}]}]},{B:"span",V:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-icon"},"\u041f\u043b\u0435\u0458\u043b\u0438\u0441\u0442\u0430",{B:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{B:"span",T:"{{playlist_length}}"},")"]}]},{B:"span",V:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-mix-icon"},"\u041c\u0438\u043a\u0441",{B:"span",G:"ytp-videowall-still-listlabel-length",T:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.vs(this);g.G(this,this.u);this.ca("click",this.D);this.ca("keypress",this.F);this.u.K(a,"videodatachange",this.C);g.X(a).F&&g.WN(a.app.R,this.element,this);this.C()},N3=function(a){g.nK(a.l,a.element);
var b=a.o.oa().videoId,c=a.o.getPlaylistId();g.SX(a.l.app,b,a.o.Xb,c,void 0,void 0)},O3=function(a){F3.call(this,a,"videowall-endscreen");
this.H=a;this.C=0;this.o=[];this.D=this.u=this.A=null;this.F=this.R=!1;this.O=null;this.ba=new g.vs(this);g.G(this,this.ba);this.I=new g.M(g.Sa(g.J,this.element,"ytp-show-tiles"),0);g.G(this,this.I);var b=new g.W({B:"button",V:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"\u041f\u0440\u0435\u0442\u0445\u043e\u0434\u043d\u043e"},J:[g.kP()]});g.G(this,b);b.g(this.element);b.ca("click",this.GF,this);this.M=new g.JC({B:"div",G:"ytp-endscreen-content"});g.G(this,this.M);this.M.g(this.element);
b=new g.W({B:"button",V:["ytp-button","ytp-endscreen-next"],L:{"aria-label":"\u0421\u043b\u0435\u0434\u0435\u045b\u0435"},J:[g.lP()]});g.G(this,b);b.g(this.element);b.ca("click",this.FF,this);this.l=new G3(a);g.G(this,this.l);g.kK(this.player,this.l.element,4);this.hide()},P3=function(a){return g.lK(a.player)&&a.wu()&&!a.D},Q3=function(a,b){return(0,g.B)(b.suggestions,function(c){c=g.PR(g.X(a.H),c);
g.G(a,c);return c})},R3=function(a){var b=a.Ne();
b!=a.R&&(a.R=b,a.player.N("autonavvisibility"))},T3=function(a){g.yK.call(this,a);
this.g=null;this.i=new g.vs(this);g.G(this,this.i);this.l=g.X(a);S3(a)?this.g=new O3(this.player):this.l.Ea?this.g=new L3(this.player):this.g=new F3(this.player);g.G(this,this.g);g.kK(this.player,this.g.element,4);this.Wz();this.i.K(a,"videodatachange",this.Wz,this);this.i.K(a,g.ND("endscreen"),this.SE,this);this.i.K(a,"crx_endscreen",this.TE,this)},S3=function(a){a=g.X(a);
return a.Ba&&!a.Ea};
g.t(F3,g.OC);F3.prototype.create=function(){this.created=!0};
F3.prototype.destroy=function(){this.created=!1};
F3.prototype.wu=function(){return!1};
F3.prototype.Ne=function(){return!1};g.t(G3,g.W);g.h=G3.prototype;g.h.Tl=function(){this.C&&(this.F.stop(),this.Ka(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.By=function(){g.NC(this,this.l.Ne())};
g.h.UJ=function(){window.focus();this.Tl()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.To=function(a){a=a||g.R(g.X(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.O()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?K3(this,!0):this.o&&this.o.start()};
g.h.cK=function(a){!g.ae(this.A.element,g.Pr(a))&&g.SR(a,this.l)&&K3(this)};
g.h.pI=function(){g.UJ(this.l,!0)};
g.h.uJ=function(a){this.l.getPresentingPlayerType();this.show();H3(this,a)};
g.h.YA=function(a){this.l.getPresentingPlayerType();this.u&&this.u.oa().videoId==a.oa().videoId||(this.u=a,E3(this,a,"hqdefault.jpg"))};
g.h.vJ=function(){this.l.getPresentingPlayerType();I3(this);this.hide()};
g.h.U=function(){I3(this);this.Tl();g.W.prototype.U.call(this)};g.t(L3,F3);g.t(M3,g.W);M3.prototype.D=function(a){g.SR(a,this.l,this.A,this.o.Xb||void 0)&&N3(this)};
M3.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.Ur(a)||(N3(this),g.Tr(a))}};
M3.prototype.C=function(){var a=this.l.getVideoData(),b=g.X(this.l);this.A=a.Nb?!1:b.i};g.t(O3,F3);g.h=O3.prototype;g.h.create=function(){F3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.A=Q3(this,a),this.u=a);this.Lf();this.ba.K(this.player,"appresize",this.Lf);this.ba.K(this.player,"onVideoAreaChange",this.Lf);this.ba.K(this.player,"videodatachange",this.HF);this.ba.K(this.player,"autonavchange",this.fr);this.ba.K(this.player,"autonavcancel",this.EF);a=this.u.autonavState;a!=this.O&&this.fr(a);this.ba.K(this.element,"transitionend",this.rL)};
g.h.destroy=function(){g.xs(this.ba);g.rf(this.o);this.o=[];this.A=null;F3.prototype.destroy.call(this);g.Tn(this.element,"ytp-show-tiles");this.I.stop();this.O=this.u.autonavState};
g.h.wu=function(){return 1!=this.u.autonavState};
g.h.show=function(){F3.prototype.show.call(this);g.Tn(this.element,"ytp-show-tiles");g.X(this.player).g?g.co(this.I):this.I.start();(this.F||this.D&&this.D!=this.u.clientPlaybackNonce)&&g.UJ(this.player,!1);P3(this)?(R3(this),2==this.u.autonavState?g.Q(g.X(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?K3(this.l,!0):H3(this.l):3==this.u.autonavState&&J3(this.l)):(g.UJ(this.player,!0),R3(this))};
g.h.hide=function(){F3.prototype.hide.call(this);J3(this.l);R3(this)};
g.h.rL=function(a){g.Pr(a)==this.element&&this.Lf()};
g.h.Lf=function(){if(this.A&&this.A.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.bK(this.H,!0),b=g.cD(this.H);b&&(b=b.ac()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.A.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,u=b<=f-2&&n>=r*m,A=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&A)n-=p*m,e+=2;else if(u)n-=r*m,b+=2;else if(A)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.qd(a.width/m||1,1,1.21);n*=g.qd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.M.element;g.Rh(a,m,n);g.zh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.A[0];c.u=f;E3(c,f,"hqdefault.jpg");g.K(this.element,"ytp-endscreen-takeover",P3(this));R3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.rd(p+this.C,l),0!=r){u=this.o[c];u||(u=new M3(this.player),this.o[c]=u,a.appendChild(u.element));A=Math.floor(n*k/e);var C=Math.floor(m*f/b),E=Math.floor(n*(k+r)/e)-A-4,F=Math.floor(m*(f+r)/b)-C-4;g.Hh(u.element,C,A);g.Rh(u.element,F,E);g.zh(u.element,"transitionDelay",(k+f)/20+"s");g.K(u.element,"ytp-videowall-still-mini",1==r);g.K(u.element,"ytp-videowall-still-large",2<r);r=u;p=this.A[p];r.o!=p&&(r.o=p,E3(r,p,g.Rn(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.Xb)&&p.itct)&&(u=r.l,g.X(u).F&&g.XN(u.app.R,r.element,p));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Xd(e.element),g.qf(e);this.o.length=c}};
g.h.HF=function(){var a=this.player.getVideoData();this.u!=a&&(this.C=0,this.A=Q3(this,a),this.u=a,this.Lf())};
g.h.FF=function(){this.C+=this.o.length;this.Lf()};
g.h.GF=function(){this.C-=this.o.length;this.Lf()};
g.h.hE=function(){return!!this.l.o};
g.h.fr=function(a){1==a?(this.F=!1,this.D=this.u.clientPlaybackNonce,I3(this.l),this.Da()&&this.Lf()):(this.F=!0,this.Da()&&P3(this)&&(2==a?H3(this.l):3==a&&J3(this.l)))};
g.h.EF=function(a){if(a){for(a=0;a<this.o.length;a++)g.oK(this.H,this.o[a].element,!0);this.fr(1)}else this.D=null,this.F=!1;this.Lf()};
g.h.Ne=function(){return this.Da()&&P3(this)};g.t(T3,g.yK);g.h=T3.prototype;g.h.Qk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!S3(this.player)||b;a=a.Mc||g.Iy(a.Ma);var c=g.sX(this.player.app);return b&&!a&&!c};
g.h.Ne=function(){return this.g.Ne()};
g.h.cE=function(){return this.Ne()?this.g.hE():!1};
g.h.U=function(){g.gK(this.player,"endscreen");g.yK.prototype.U.call(this)};
g.h.load=function(){g.yK.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.yK.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.SE=function(a){this.Qk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.TE=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Wz=function(){g.gK(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.KD(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.G(this,a);var b=new g.KD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.G(this,b);g.dK(this.player,[a,b])};g.UU.endscreen=T3;})(_yt_player);
