(function(g){var window=this;var $pa=function(a,b){return g.Vb(a,b)},c5=function(){},aqa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.Fa(a))return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},bqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||g.Fa(a))(0,g.z)(a,b,void 0);else{if(a.Hd&&"function"==typeof a.Hd)var c=a.Hd();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.Na(a)||g.Fa(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=aqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},d5=function(a){g.Vm(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.H)()).toString(36));
return a},e5=function(a,b,c){g.Ma(c)||(c=[String(c)]);
g.$m(a.l,b,c)},f5=function(a){return(a=g.to(a))?new ActiveXObject(a):new XMLHttpRequest},g5=function(a,b){return b+" ["+a.aa+" "+a.D+" "+a.getStatus()+"]"},cqa=function(a){return"content-type"==a.toLowerCase()},h5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.v.clearTimeout(a.F),a.F=null)},dqa=function(a){return g.Md&&g.od(9)&&g.Ha(a.timeout)&&g.Ea(a.ontimeout)},i5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},j5=function(a,b){if(a.g){h5(a);
var c=a.g,d=a.P[0]?g.Ja:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},k5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;i5(a);j5(a)},l5=function(a){return a.g?a.g.readyState:0},m5=function(a){if(a.i&&"undefined"!=typeof g.hY)if(a.P[1]&&4==l5(a)&&2==a.getStatus())g5(a,"Local request error detected and ignored");
else if(a.C&&4==l5(a))g.Gg(a.iw,0,a);else if(a.dispatchEvent("readystatechange"),4==l5(a)){g5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.D));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!eqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<l5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";i5(a)}}finally{j5(a)}}},n5=function(a){g.Sf.call(this);
this.headers=new g.Km;this.M=a||null;this.i=!1;this.P=this.g=null;this.aa=this.D="";this.u=0;this.l="";this.o=this.W=this.C=this.O=!1;this.A=0;this.F=null;this.Z="";this.I=this.R=!1},o5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},fqa=function(a,b){var c=[];
g.Lk(b,function(d){try{var e=g.Io.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ea(e)?g.Ho(e)&&c.push(d):c.push(d)},a);
return c},gqa=function(a,b){var c=fqa(a,b);
(0,g.z)(c,function(d){g.Io.prototype.remove.call(this,d)},a)},p5=function(a){if(a.cd){if(a.cd.locationOverrideToken)return{locationOverrideToken:a.cd.locationOverrideToken};
if(null!=a.cd.latitudeE7&&null!=a.cd.longitudeE7)return{latitudeE7:a.cd.latitudeE7,longitudeE7:a.cd.longitudeE7}}return null},hqa=function(a,b){g.ab(a,b)||a.push(b)},q5=function(a){var b=0,c;
for(c in a)b++;return b},r5=function(a,b){var c=b instanceof g.yc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.zc(c)},iqa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},jqa=function(a,b,c,d){var e=new g.Nm(null,void 0);
a&&g.Om(e,a);b&&g.Pm(e,b);c&&g.Qm(e,c);d&&(e.i=d);return e},s5=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return iqa(a)},t5=function(){this.g=[];
this.i=[]},u5=function(a,b){g.Np[a]=!0;
var c=g.Lp();c&&c.publish.apply(c,arguments);g.Np[a]=!1},v5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Km;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",kqa(this,a.capabilities||""),lqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},kqa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Sa($pa,mqa)).forEach(function(c){a.capabilities.add(c)})},lqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},w5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},x5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},y5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},nqa=function(a){return new w5(a)},z5=function(a){return g.Ma(a)?(0,g.B)(a,nqa):[]},A5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},B5=function(a){return g.Ma(a)?"["+(0,g.B)(a,A5).join(",")+"]":"null"},C5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},oqa=function(a){return(0,g.B)(a,function(b){return{key:b.id,
name:b.name}})},D5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},E5=function(a,b){return g.Ya(a,function(c){return x5(c,b)})},F5=function(a){try{var b=(0,g.et)(),c=(0,g.dt)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},pqa=function(){var a=(0,g.dt)();
a&&gqa(a,a.g.lf(!0))},G5=function(){var a=g.gt("yt-remote-connected-devices")||[];
g.rb(a);return a},qqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.B)(a,function(d,e){return 0==e?d:d.substring(c.length)})},H5=function(a){g.ft("yt-remote-connected-devices",a,86400)},J5=function(){if(I5)return I5;
var a=g.gt("yt-remote-device-id");a||(a=C5(),g.ft("yt-remote-device-id",a,31536E3));for(var b=G5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return I5=d},K5=function(){var a=G5(),b=J5();
g.ab(a,b);g.ht()&&g.tb(a,b);a=qqa(a);if(0==a.length)try{g.hs("remote_sid")}catch(c){}else try{g.gs("remote_sid",a.join(","),-1)}catch(c){}},L5=function(){return g.gt("yt-remote-session-browser-channel")},M5=function(){return g.gt("yt-remote-local-screens")||[]},N5=function(){g.ft("yt-remote-lounge-token-expiration",!0,86400)},rqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.B)(M5(),function(d){return d.loungeToken}),c=(0,g.B)(a,function(d){return d.loungeToken});
(0,g.jj)(c,function(d){return!g.ab(b,d)})&&N5();
g.ft("yt-remote-local-screens",a,31536E3)},sqa=function(a,b){g.ft("yt-remote-session-browser-channel",a);
g.ft("yt-remote-session-screen-id",b);var c=G5(),d=J5();g.ab(c,d)||c.push(d);H5(c);K5()},O5=function(a){a||(F5("yt-remote-session-screen-id"),F5("yt-remote-session-video-id"));
K5();a=G5();g.db(a,J5());H5(a)},Q5=function(){if(!P5){var a=g.So();
a&&(P5=new g.Co(a))}return P5?!!P5.get("yt-remote-use-staging-server"):!1},R5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},S5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},U5=function(a){a.length?T5(a.shift(),function(){U5(a)}):V5()},tqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},T5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},V5=function(){var a=S5();
a&&a(!1,"No cast extension found")},W5=function(){if(uqa){var a=2,b=S5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;T5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",V5,c)}},vqa=function(){W5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);U5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},X5=function(a,b,c){g.D.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Wc=b;this.u=(0,g.x)(this.mD,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},Y5=function(){},Z5=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.ba=new g.an(this);this.i=new g.Fg;this.i.setInterval(250)},a6=function(a,b,c){a.Wh=1;
a.Yf=d5(b.clone());a.uh=c;a.u=!0;$5(a,null)},b6=function(a,b,c,d,e){a.Wh=1;
a.Yf=d5(b.clone());a.uh=null;a.u=c;e&&(a.cA=!1);$5(a,d)},$5=function(a,b){a.Fi=(0,g.H)();
c6(a);a.Fg=a.Yf.clone();e5(a.Fg,"t",a.A);a.kl=0;a.tc=a.g.yp(a.g.Sk()?b:null);0<a.bq&&(a.In=new g.Al((0,g.x)(a.jB,a,a.tc),a.bq));a.ba.ca(a.tc,"readystatechange",a.dM);var c=a.bh?g.cc(a.bh):{};a.uh?(a.mo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.Fg,a.mo,a.uh,c)):(a.mo="GET",a.cA&&!g.Od&&(c.Connection="close"),a.tc.send(a.Fg,a.mo,null,c));a.g.te(1)},j6=function(a,b,c){for(var d=!0;!a.Qg&&a.kl<c.length;){var e=wqa(a,c);
if(e==d6){4==b&&(a.qg=4,e6(15),d=!1);break}else if(e==f6){a.qg=4;e6(16);d=!1;break}else g6(a,e)}4==b&&0==c.length&&(a.qg=1,e6(17),d=!1);a.xe=a.xe&&d;d||(h6(a),i6(a))},wqa=function(a,b){var c=a.kl,d=b.indexOf("\n",c);
if(-1==d)return d6;c=Number(b.substring(c,d));if(isNaN(c))return f6;d+=1;if(d+c>b.length)return d6;var e=b.substr(d,c);a.kl=d+c;return e},m6=function(a,b){a.Fi=(0,g.H)();
c6(a);var c=b?window.location.hostname:"";a.Fg=a.Yf.clone();g.Vm(a.Fg,"DOMAIN",c);g.Vm(a.Fg,"t",a.A);try{a.Be=new ActiveXObject("htmlfile")}catch(n){h6(a);a.qg=7;e6(22);i6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in k6)k=k6[l];else if(l in l6)k=k6[l]=l6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
k6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Sc(g.rc("b/12014412"),d+"</body></html>");a.Be.open();a.Be.write(g.Nc(c));a.Be.close();a.Be.parentWindow.m=(0,g.x)(a.uL,a);a.Be.parentWindow.d=(0,g.x)(a.gz,a,!0);a.Be.parentWindow.rpcClose=(0,g.x)(a.gz,a,!1);c=a.Be.createElement("DIV");a.Be.parentWindow.document.body.appendChild(c);d=g.Dc(a.Fg.toString());d=g.Zc(g.Ac(d));d=g.Sc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Tc(c,d);a.g.te(1)},c6=function(a){a.kt=(0,g.H)()+a.o;
n6(a,a.o)},n6=function(a,b){if(null!=a.Wi)throw Error("WatchDog timer not null");
a.Wi=o6((0,g.x)(a.EL,a),b)},p6=function(a){a.Wi&&(g.v.clearTimeout(a.Wi),a.Wi=null)},i6=function(a){a.g.gw()||a.Qg||a.g.vn(a)},h6=function(a){p6(a);
g.qf(a.In);a.In=null;a.i.stop();g.cn(a.ba);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.Be&&(a.Be=null)},g6=function(a,b){try{a.g.az(a,b),a.g.te(4)}catch(c){}},r6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;q6(a,b,function(k){k?c(!0):g.v.setTimeout(function(){r6(a,b,c,d,f)},f)})}},q6=function(a,b,c){var d=new Image;
d.onload=function(){try{s6(d),c(!0)}catch(e){}};
d.onerror=function(){try{s6(d),c(!1)}catch(e){}};
d.onabort=function(){try{s6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{s6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
r5(d,a)},s6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},t6=function(a){this.g=a;
this.i=new Y5},v6=function(a){var b=u6(a.g,a.kj,"/mail/images/cleardot.gif");
d5(b);r6(b.toString(),5E3,(0,g.x)(a.sC,a),3,2E3);a.te(1)},x6=function(a){var b=a.g.F;
if(null!=b)e6(5),b?(e6(11),w6(a.g,a,!1)):(e6(12),w6(a.g,a,!0));else if(a.Cd=new Z5(a,void 0,void 0,void 0),a.Cd.bh=a.Yp,b=a.g,b=u6(b,b.Sk()?a.Sj:null,a.Zp),e6(5),!g.Md||g.pd(10))e5(b,"TYPE","xmlhttp"),b6(a.Cd,b,!1,a.Sj,!1);else{e5(b,"TYPE","html");var c=a.Cd;a=!!a.Sj;c.Wh=3;c.Yf=d5(b.clone());m6(c,a)}},y6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new Y5;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},xqa=function(a,b){this.g=a;
this.map=b;this.context=null},z6=function(a){g.sf.call(this,"statevent",a)},A6=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},B6=function(a){g.sf.call(this,"serverreachability",a)},F6=function(a){C6(a);
if(3==a.g){var b=a.zk++,c=a.hm.clone();g.Vm(c,"SID",a.l);g.Vm(c,"RID",b);g.Vm(c,"TYPE","terminate");D6(a,c);b=new Z5(a,a.l,b,void 0);b.Wh=2;b.Yf=d5(c.clone());r5(new Image,b.Yf.toString());b.Fi=(0,g.H)();c6(b)}E6(a)},H6=function(a){a.LC(1,0);
a.hm=u6(a,null,a.Xp);G6(a)},C6=function(a){a.gg&&(a.gg.abort(),a.gg=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.nf&&(g.v.clearTimeout(a.nf),a.nf=null);I6(a);a.yd&&(a.yd.cancel(),a.yd=null);a.mg&&(g.v.clearTimeout(a.mg),a.mg=null)},J6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new xqa(a.KH++,b));2!=a.g&&3!=a.g||G6(a)},G6=function(a){a.yd||a.mg||(a.mg=o6((0,g.x)(a.fz,a),0),a.Qh=0)},M6=function(a,b){if(1==a.g){if(!b){a.zk=Math.floor(1E5*Math.random());
var c=a.zk++,d=new Z5(a,"",c,void 0);d.bh=null;var e=K6(a),f=a.hm.clone();g.Vm(f,"RID",c);g.Vm(f,"CVER","1");D6(a,f);a6(d,f,e);a.yd=d;a.g=2}}else 3==a.g&&(b?L6(a,b):0==a.i.length||a.yd||L6(a))},L6=function(a,b){if(b)if(6<a.Rg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.zk-1;var d=K6(a)}else c=b.C,d=b.uh;else c=a.zk++,d=K6(a);var e=a.hm.clone();g.Vm(e,"SID",a.l);g.Vm(e,"RID",c);g.Vm(e,"AID",a.ji);D6(a,e);c=new Z5(a,a.l,c,a.Qh+1);c.bh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yd=c;a6(c,e,d)},D6=function(a,b){if(a.Tc){var c=a.Tc.Gv();
c&&g.Lb(c,function(d,e){g.Vm(b,e,d)})}},K6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Rg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Rg?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},N6=function(a){a.Sb||a.nf||(a.C=1,a.nf=o6((0,g.x)(a.ez,a),0),a.Jh=0)},P6=function(a){if(a.Sb||a.nf||3<=a.Jh)return!1;
a.C++;a.nf=o6((0,g.x)(a.ez,a),O6(a,a.Jh));a.Jh++;return!0},w6=function(a,b,c){a.ko=c;
a.Ie=b.Af;a.A||H6(a)},I6=function(a){null!=a.Vg&&(g.v.clearTimeout(a.Vg),a.Vg=null)},O6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},R6=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.x)(a.IM,a);c||(c=new g.Nm("//www.google.com/images/cleardot.gif"),d5(c));q6(c.toString(),1E4,d)}else e6(2);Q6(a,b)},Q6=function(a,b){a.g=0;
a.Tc&&a.Tc.Iu(b);E6(a);C6(a)},E6=function(a){a.g=0;
a.Ie=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.kp();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Tc.kp(b)}},u6=function(a,b,c){var d=g.Wm(c);
if(""!=d.g)b&&g.Pm(d,b+"."+d.g),g.Qm(d,d.u);else{var e=window.location;d=jqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.xj&&g.Lb(a.xj,function(f,k){g.Vm(d,k,f)});
g.Vm(d,"VER",a.Rg);D6(a,d);return d},o6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},e6=function(a){S6.dispatchEvent(new z6(S6,a))},T6=function(){},yqa=function(a,b){this.action=a;
this.params=b||{}},U6=function(a,b){g.D.call(this);
this.g=new g.M(this.mL,0,this);g.G(this,this.g);this.Wc=5E3;this.i=0;if(g.Oa(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},V6=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Bo;this.i=new U6(this.mM,this);this.g=null;this.fb=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},zqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.ko,sessionId:a.g.l,arrayId:a.g.ji}},W6=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&M6(a.g),F6(a.g));a.D=0},X6=function(a){return!!a.g&&3==a.g.g},Aqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},Y6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.i=!1))},Z6=function(a,b){var c=a.g;
if(g.Ea(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.ch(c+b,{})},$6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.o,d,!0),onError:g.Sa(a.l,e),ie:g.Sa(a.u,e)};c&&(a.tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Fq(b,a)},Bqa=function(){var a=a7;
b7();c7.push(a);d7(c7)},e7=function(a,b){b7();
var c=c7,d=Cqa(a,String(b));0==c.length?Dqa(d):(d7(c),(0,g.z)(c,function(e){e(d)}))},b7=function(){c7||(c7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",c7,void 0))},Dqa=function(a){var b=(f7+1)%50;
f7=b;g7[b]=a;h7||(h7=49==b)},d7=function(a){var b=g7;
if(b[0]){var c=f7,d=h7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
g7=Array(50);f7=-1;h7=!1}},Cqa=function(a,b){var c=((0,g.H)()-Eqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},i7=function(a){g.P.call(this);
this.C=a;this.g=[]},j7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Fqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Yd)(a.g,function(f){return!!D5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=j7(a,b[d])||c;return c},Gqa=function(a,b){var c=a.g.length;
a.g=(0,g.Yd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},k7=function(a,b,c,d){g.P.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},m7=function(a){i7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;l7(this);this.info("Initializing with "+B5(this.g))},n7=function(a){if(a.g.length){var b=(0,g.B)(a.g,function(d){return d.id}),c=Z6(a.l,"/pairing/get_lounge_token_batch");
$6(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.wD,a),(0,g.x)(a.vD,a))}},l7=function(a){var b=z5(M5());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return Fqa(a,b)},o7=function(a,b){rqa((0,g.B)(a.g,y5));
b&&N5()},q7=function(a,b){g.P.call(this);
this.A=b;var c=g.gt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;p7("Initialized with "+g.Kg(this.g))},r7=function(a,b,c){var d=Z6(a.u,"/pairing/get_screen_availability");
$6(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},s7=function(a,b){a:if(q5(b)!=q5(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(p7("Updated online screens: "+g.Kg(a.g)),a.g=b,a.N("screenChange"));Hqa(a)},t7=function(a){isNaN(a.l)||g.Kp(a.l);
a.l=g.Ip((0,g.x)(a.os,a),0<a.o&&a.o<(0,g.H)()?2E4:1E4)},p7=function(a){e7("OnlineScreenService",a)},u7=function(a){var b={};
(0,g.z)(a.A(),function(c){c.token?b[c.token]=c.id:this.Hb("Requesting availability of screen w/o lounge token.")});
return b},Hqa=function(a){a=g.Sb(g.Mb(a.g,function(b){return b}));
g.rb(a);a.length?g.ft("yt-remote-online-screen-ids",a.join(","),60):F5("yt-remote-online-screen-ids")},v7=function(a){i7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Iqa(this)},x7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Id();if(k=(c?E5(k,c):null)||E5(k,b)){k.uuid=b;var l=w7(a,k);r7(a.i,l,function(m){e(m?l:null)})}else c?Jqa(a,c,(0,g.x)(function(m){var n=w7(this,new w5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));r7(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},y7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Jqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Fq(Z6(a.A,"/pairing/get_lounge_token_batch"),e)},z7=function(a){a.g=a.l.Id();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+B5(a.g))},Iqa=function(a){A7(a);
a.l=new m7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.ED,a));z7(a);a.o=z5(g.gt("yt-remote-automatic-screen-cache")||[]);A7(a);a.info("Initializing automatic screens: "+B5(a.o));a.i=new q7(a.A,(0,g.x)(a.Id,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=E5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.ft("yt-remote-automatic-screen-cache",(0,g.B)(a.o,y5)));A7(a);a.u[b.uuid]=b.id;g.ft("yt-remote-device-id-map",a.u,31536E3);return b},A7=function(a){a.u=g.gt("yt-remote-device-id-map")||{}},B7=function(a,b,c){g.P.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},C7=function(a,b){e7(a.P,b)},E7=function(a,b){B7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.nN,this);this.u=(0,g.x)(this.PL,this);this.o=g.Ip((0,g.x)(function(){D7(this,null)},this),12E4)},Kqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){C7(this,"Failed to send message: getMdxSessionStatus.")},a)):C7(a,"Sending yt message without session: "+g.Kg(b))},D7=function(a,b){g.Kp(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.xn,a),d=(0,g.x)(a.Ld,a);a.Wv(b,c,d,5)}}else a.Ld(Error("Waiting for session status timed out."))},F7=function(a,b,c){B7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.C=g.Ja;this.A=NaN;this.I=(0,g.x)(this.qN,this);this.g=g.Ja},G7=function(a){a.g=a.F.oB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ja;
this.xn(b)},a),(0,g.x)(function(b){this.g=g.Ja;
this.Ld(b)},a))},H7=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}Q5()&&(b.env_useStageMdx=1);return g.ah(b)},I7=function(a,b){B7.call(this,a,b,"ManualSession");
this.g=g.Ip((0,g.x)(this.li,this,null),150)},J7=function(a,b,c,d){g.P.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.vK,this)},K7=function(a,b){return b?g.Ya(a.l,function(c){return x5(b,c.label)},a):null},L7=function(a){e7("Controller",a)},a7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},M7=function(a){return a.u||!!a.l.length||!!a.g},N7=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.dz,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.li(null)):a.N("yt-remote-cast2-session-change",null))},O7=function(a){var b=a.i.nB(),c=a.g&&a.g.i;
a=(0,g.B)(b,function(d){c&&x5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=K7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Oqa=function(a,b,c,d,e,f,k){Lqa()?Mqa(b,e,f,k)&&(Q7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?R7(a,c):(window.__onGCastApiAvailable=function(l,m){l?R7(a,c):(S7("Failed to load cast API: "+m),T7(!1),Q7(!1),F5("yt-remote-cast-available"),F5("yt-remote-cast-receiver"),U7(),c(!1))},d?g.Vp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?vqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?V5():(W5(),U5(Nqa.map(tqa))))):P7("Cannot initialize because not running Chrome")},U7=function(){P7("dispose");
var a=V7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);W7(!1);g.Qp(X7);X7.length=0},Y7=function(){return!!g.gt("yt-remote-cast-installed")},Z7=function(){var a=g.gt("yt-remote-cast-receiver");
return a?a.friendlyName:null},$7=function(){P7("clearCurrentReceiver");
F5("yt-remote-cast-receiver")},a8=function(){return Y7()?V7()?V7().getCastSession():(S7("getCastSelector: Cast is not initialized."),null):(S7("getCastSelector: Cast API is not installed!"),null)},c8=function(){Y7()?V7()?b8()?(P7("Requesting cast selector."),V7().requestSession()):(P7("Wait for cast API to be ready to request the session."),X7.push(g.Pp("yt-remote-cast2-api-ready",c8))):S7("requestCastSelector: Cast is not initialized."):S7("requestCastSelector: Cast API is not installed!")},d8=function(a,
b){b8()?V7().setConnectedScreenStatus(a,b):S7("setConnectedScreenStatus called before ready.")},Lqa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Ow||a},Pqa=function(a,b){V7().init(a,b)},Mqa=function(a,b,c,d){var e=!1;
V7()||(a=new J7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.ft("yt-remote-cast-available",f);u5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){P7("onReceiverSelected: "+f.friendlyName);
g.ft("yt-remote-cast-receiver",f);u5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){P7("onReceiverResumed: "+f.friendlyName);
g.ft("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){P7("onSessionChange: "+A5(f));
f||F5("yt-remote-cast-receiver");u5("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
P7("cloudview.createSingleton_: "+e);return e},V7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},R7=function(a,b){T7(!0);
Q7(!1);Pqa(a,function(c){c?(W7(!0),g.Sp("yt-remote-cast2-api-ready")):(S7("Failed to initialize cast API."),T7(!1),F5("yt-remote-cast-available"),F5("yt-remote-cast-receiver"),U7());b(c)})},P7=function(a){e7("cloudview",a)},S7=function(a){e7("cloudview",a)},T7=function(a){P7("setCastInstalled_ "+a);
g.ft("yt-remote-cast-installed",a)},b8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},W7=function(a){P7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},Q7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},e8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Je=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},f8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Je=!1;a.hasNext=!1;a.C=0;a.A=(0,g.H)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},g8=function(a){return 1==a.playerState?((0,g.H)()-a.A)/1E3:0},h8=function(a,b){a.C=b;
a.A=(0,g.H)()},i8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},j8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&f8(a)},k8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Je;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},n8=function(a,b){g.P.call(this);
this.g=0;this.o=a;this.A=[];this.u=new t5;this.l=this.i=null;this.F=(0,g.x)(this.sI,this);this.C=(0,g.x)(this.Ck,this);this.D=(0,g.x)(this.rI,this);this.H=(0,g.x)(this.GI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.nt,this),l8(this))):c=3;0!=c&&(b?this.nt(c):g.Ip((0,g.x)(function(){this.nt(c)},this),0));
var d=a8();d&&m8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},o8=function(a){return new e8(a.o.getPlayerContextData())},l8=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Sa(this.sK,b),this))},a)},p8=function(a){(0,g.z)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},q8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},s8=function(a,b,c){var d=o8(a);
h8(d,c);-1E3!=d.playerState&&(d.playerState=b);r8(a,d)},t8=function(a,b,c){a.o.sendMessage(b,c)},r8=function(a,b){p8(a);
a.o.setPlayerContextData(k8(b));l8(a)},m8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.Ck(null));
a.l=b;a.l&&(e7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.Ck(a.l.media[0]))},u8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=o8(a);b.contentId!=d.videoId&&e7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;h8(d,a.i.getEstimatedTime());r8(a,d)}else e7("CP","No cast media video. Ignoring state update.")},v8=function(a,b,c){return(0,g.x)(function(d){this.Hb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hb("Retrying "+b+" using MDx browser channel."),t8(this,b,c))},a)},w8=function(a,b,c){g.P.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.P=[];this.o=this.A=this.l=this.Oa=this.g=null;this.O=a;this.P.push(g.Nr(window,"beforeunload",(0,g.x)(this.pD,this)));this.i=[];this.Oa=new e8;this.M=b.id;this.g=Qqa(this,c);this.g.subscribe("handlerOpened",this.wI,this);this.g.subscribe("handlerClosed",this.tI,this);this.g.subscribe("handlerError",this.uI,this);this.g.subscribe("handlerMessage",this.vI,this);Aqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.ht()&&g.ft("yt-remote-session-video-id",d)},this)},x8=function(a){e7("conn",a)},Qqa=function(a,b){return new V6(Z6(a.O,"/bc"),b)},y8=function(a,b){a.N("proxyStateChange",b)},Rqa=function(a){a.u=g.Ip((0,g.x)(function(){x8("Connecting timeout");
this.Nh(1)},a),2E4)},z8=function(a){g.Kp(a.u);
a.u=NaN},A8=function(a){g.Kp(a.H);
a.H=NaN},Sqa=function(a){B8(a);
a.F=g.Ip((0,g.x)(function(){C8(this,"getNowPlaying")},a),2E4)},B8=function(a){g.Kp(a.F);
a.F=NaN},E8=function(a,b){b&&(z8(a),A8(a));
b==(X6(a.g)&&isNaN(a.u))?b&&(y8(a,1),C8(a,"getSubtitlesTrack")):b?(a.Tv()&&a.Oa.reset(),y8(a,1),C8(a,"getNowPlaying"),D8(a)):a.Nh(1)},Tqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Yb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.N("remotePlayerChange"))},F8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;j8(a.Oa,c,d);a.N("remoteQueueChange")},Uqa=function(a,b){b.params=b.params||{};
F8(a,b);G8(a,b);a.N("autoplayDismissed")},G8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
h8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.D=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?Sqa(a):B8(a);a.N("remotePlayerChange")},Vqa=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);h8(a.Oa,isNaN(c)?0:c);a.N("remotePlayerChange")}},Wqa=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.N("remotePlayerChange")},Xqa=function(a,b){a.A=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},Yqa=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Je="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.N("previousNextChange")},D8=function(a){g.Kp(a.D);
a.D=g.Ip((0,g.x)(a.Nh,a,1),864E5)},C8=function(a,b,c){c?x8("Sending: action="+b+", params="+g.Kg(c)):x8("Sending: action="+b);
a.g.sendMessage(b,c)},H8=function(a){i7.call(this,"ScreenServiceProxy");
this.Vc=a;this.i=[];this.i.push(this.Vc.$_s("screenChange",(0,g.x)(this.lN,this)));this.i.push(this.Vc.$_s("onlineScreenChange",(0,g.x)(this.XJ,this)))},cra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Ap("MDX_CONFIG")||b;pqa();K5();I8||(I8=new Y6(b?b.loungeApiHost:void 0),Q5()&&(I8.g="/api/loungedev"));J8||(J8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",J8,void 0));Zqa();var c=K8();if(!c){var d=new v7(I8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=K8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Oqa(a,d,function(m){m?L8()&&d8(L8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){u5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),M8("Initializing: "+g.Kg(b)),N8.push(g.Pp("yt-remote-cast2-availability-change",function(){u5("yt-remote-receiver-availability-change")})),N8.push(g.Pp("yt-remote-cast2-receiver-selected",function(){O8(null);
u5("yt-remote-auto-connect","cast-selector-receiver")})),N8.push(g.Pp("yt-remote-cast2-receiver-resumed",function(){u5("yt-remote-receiver-resumed","cast-selector-receiver")})),N8.push(g.Pp("yt-remote-cast2-session-change",$qa)),N8.push(g.Pp("yt-remote-connection-change",function(m){m?d8(L8(),"YouTube TV"):P8()||(d8(null,null),$7())})),a=Q8(),b.isAuto&&(a.id+="#dial"),g.wq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),M8(" -- with channel params: "+
g.Kg(a)),ara(a),c.start(),L8()||bra())},dra=function(){var a=R8();
Y7()&&g.gt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},R8=function(){var a=K8().Vc.$_gos();
var b=S8();b&&T8()&&(D5(a,b)||a.push(b));return oqa(a)},U8=function(){var a=era();
!a&&Y7()&&Z7()&&(a={key:"cast-selector-receiver",name:Z7()});return a},era=function(){var a=R8(),b=S8();
b||(b=P8());return g.Ya(a,function(c){return b&&x5(b,c.key)?!0:!1})},S8=function(){var a=L8();
if(!a)return null;var b=K8().Id();return E5(b,a)},$qa=function(a){M8("remote.onCastSessionChange_: "+A5(a));
if(a){var b=S8();b&&b.id==a.id?d8(b.id,"YouTube TV"):(b&&V8(),W8(a,1))}else T8()&&V8()},V8=function(){b8()?V7().stopSession():S7("stopSession called before API ready.");
var a=T8();a&&(a.disconnect(1),X8(null))},Y8=function(){var a=T8();
return!!a&&3!=a.getProxyState()},M8=function(a){e7("remote",a)},K8=function(){if(!Z8){var a=g.w("yt.mdx.remote.screenService_");
Z8=a?new H8(a):null}return Z8},L8=function(){return g.w("yt.mdx.remote.currentScreenId_")},$8=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},a9=function(){return g.w("yt.mdx.remote.connectData_")},O8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},T8=function(){return g.w("yt.mdx.remote.connection_")},X8=function(a){var b=T8();
O8(null);a||$8("");g.Ia("yt.mdx.remote.connection_",a,void 0);J8&&((0,g.z)(J8,function(c){c(a)}),J8.length=0);
b&&!a?u5("yt-remote-connection-change",!1):!b&&a&&u5("yt-remote-connection-change",!0)},P8=function(){var a=g.ht();
if(!a)return null;var b=K8().Id();return E5(b,a)},W8=function(a,b){S8()&&S8();
if(b9)c9=a;else{$8(a.id);var c=new w8(I8,a,Q8());c.connect(b,a9());c.subscribe("beforeDisconnect",function(d){u5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){T8()&&X8(null)});
X8(c)}},bra=function(){var a=P8();
a?(M8("Resume connection to: "+A5(a)),W8(a,0)):(O5(),$7(),M8("Skipping connecting because no session screen found."))},Zqa=function(){var a=Q8();
if(g.Yb(a)){a=J5();var b=g.gt("yt-remote-session-name")||"",c=g.gt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},Q8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},ara=function(a){a?(g.ft("yt-remote-session-app",a.app),g.ft("yt-remote-session-name",a.name)):(F5("yt-remote-session-app"),F5("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},d9=function(a,b,c){g.D.call(this);
this.u=a;this.i=b;this.l=new g.vs(this);g.G(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.rJ);this.l.K(b,"captionschanged",this.qI);this.l.K(b,"captionssettingschanged",this.CA);this.l.K(b,"videoplayerreset",this.yn);this.l.K(b,"mdxautoplaycancel",this.rC);this.O=this.l.K(b,"onVolumeChange",this.Oy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Zy,this);c.subscribe("remotePlayerChange",this.Ek,this);c.subscribe("remoteQueueChange",this.yn,this);c.subscribe("autoplayUpNext",this.Dy,
this);c.subscribe("previousNextChange",this.Wy,this);c.subscribe("nowAutoplaying",this.Sy,this);c.subscribe("autoplayDismissed",this.Cy,this);this.suggestion=null;this.F=new g.iC(64);this.o=new g.M(this.AA,500,this);g.G(this,this.o);this.A=new g.M(this.BA,1E3,this);g.G(this,this.A);this.I=new X5(this.SM,0,this);g.G(this,this.I);this.C={};this.P=new g.M(this.aB,1E3,this);g.G(this,this.P);this.H=new g.Al(this.NF,1E3,this);g.G(this,this.H);this.M=g.Ja;this.CA();this.yn();this.Ek()},e9=function(a,b){a.u.Kc(b,
a.i.getVideoData().lengthSeconds)},g9=function(a){e9(a,0);
a.o.stop();f9(a,new g.iC(64))},i9=function(a,b){if(h9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.pA(a.i.getVideoData(1).videoId,c);a.C=o8(a.g).g}},j9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Df,p5(c));f9(a,new g.iC(1))},k9=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{GQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},h9=function(a){return o8(a.g).videoId==a.i.getVideoData(1).videoId},f9=function(a,b){a.A.stop();
var c=a.F;if(!g.oC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.$J(a.i,d);a.F=b;l9(a.u,c,b)}},m9=function(){g.W.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",T:"\u041e\u0434\u0458\u0430\u0432\u0459\u0435\u043d\u0438 \u0441\u0442\u0435"},{B:"div",G:"ytp-mdx-popup-description",T:"\u0412\u0438\u0434\u0435\u043e \u0441\u043d\u0438\u043c\u0446\u0438 \u043a\u043e\u0458\u0435 \u0433\u043b\u0435\u0434\u0430\u0442\u0435 \u043c\u043e\u0433\u0443 \u0434\u0430 \u0441\u0435 \u0434\u043e\u0434\u0430\u0458\u0443 \u0443 \u0438\u0441\u0442\u043e\u0440\u0438\u0458\u0443 \u0433\u043b\u0435\u0434\u0430\u045a\u0430 \u043d\u0430 \u0422\u0412-\u0443 \u0438 \u0434\u0430 \u0443\u0442\u0438\u0447\u0443 \u043d\u0430 \u043f\u0440\u0435\u043f\u043e\u0440\u0443\u043a\u0435 \u043d\u0430 \u0422\u0412-\u0443. \u0414\u0430 \u0431\u0438\u0441\u0442\u0435 \u0442\u043e \u0441\u043f\u0440\u0435\u0447\u0438\u043b\u0438, \u043e\u0442\u043a\u0430\u0436\u0438\u0442\u0435 \u0438 \u043f\u0440\u0438\u0458\u0430\u0432\u0438\u0442\u0435 \u0441\u0435 \u043d\u0430 YouTube \u0441\u0430 \u0441\u0432\u043e\u0433 \u0440\u0430\u0447\u0443\u043d\u0430\u0440\u0430."},
{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-cancel"],T:"\u041e\u0442\u043a\u0430\u0436\u0438"},{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-confirm"],T:"\u041f\u043e\u0442\u0432\u0440\u0434\u0438"}]}]}]});this.l=new g.TP(this,250);g.G(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},o9=function(a){g.W.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.iP()]},{B:"div",G:"ytp-remote-display-status-text",T:"{{statustext}}"}]}]});this.l=new g.TP(this,250);g.G(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);n9(this,g.WJ(a))},n9=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.hN("\u0413\u0440\u0435\u0448\u043a\u0430 \u043d\u0430 $RECEIVER_NAME",c):g.pC(b)||g.U(b,4)?g.hN("\u0420\u0435\u043f\u0440\u043e\u0434\u0443\u043a\u0443\u0458\u0435 \u0441\u0435 \u043d\u0430 $RECEIVER_NAME",c):g.hN("\u041f\u043e\u0432\u0435\u0437\u0430\u043d \u043d\u0430 $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},p9=function(a,b){g.DT.call(this,"\u041f\u0443\u0441\u0442\u0438 \u043d\u0430",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},q9=function(a){g.yK.call(this,a);
this.i={key:C5(),name:"\u041e\u0432\u0430\u0458 \u0440\u0430\u0447\u0443\u043d\u0430\u0440"};this.u=null;this.o=[];this.C=this.g=null;this.A=[this.i];this.l=this.i;this.mk=new g.iC(64);this.H=0;this.Lm=-1;if(!g.Oy(g.X(this.player))){a=this.player;var b=g.cD(a);b&&(b=b.en())&&(b=new p9(a,b),g.G(this,b));b=new o9(a);g.G(this,b);g.kK(a,b.element,4);this.F=new m9;g.G(this,this.F);g.kK(a,this.F.element,4);this.D=!!P8()}},l9=function(a,b,c){a.mk=c;
a.player.N("presentingplayerstatechange",new g.tD(c,b))},r9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)V8();
else{var c;if(c=g.Q(g.X(a.player).experiments,"mdx_enable_privacy_disclosure"))c=g.Ap("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.Ap("SESSION_INDEX")||g.Ap("LOGGED_IN"));c&&!a.D&&(a.player.pauseVideo(),a.F.l.show(),T8()||(b9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,
playerParams:c.playerParams,clickTrackingParams:c.Df,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=p5(c))&&(d.locationInfo=c);c=d}else c=null;M8("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(O8(c||null),b8()?V7().setLaunchParams(c||null):S7("setLaunchParams called before ready.")):!c&&Y8()&&L8()==b.key?u5("yt-remote-connection-change",!0):(V8(),O8(c||null),c=K8().Id(),(c=E5(c,b.key))&&W8(c,1))}},eqa=/^https?$/i,fra=["POST",
"PUT"];g.y(n5,g.Sf);g.h=n5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.aa=b;this.O=!1;this.i=!0;this.g=this.M?f5(this.M):f5(g.DY);this.P=this.M?this.M.getOptions():g.DY.getOptions();this.g.onreadystatechange=(0,g.x)(this.iw,this);try{c5(g5(this,"Opening Xhr")),this.W=!0,this.g.open(b,String(a),!0),this.W=!1}catch(f){c5(g5(this,"Error opening Xhr: "+f.message));k5(this,f);return}a=c||
"";var e=this.headers.clone();d&&bqa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Hd(),cqa);c=g.v.FormData&&a instanceof g.v.FormData;!g.ab(fra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{h5(this),0<this.A&&(this.I=dqa(this.g),c5(g5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.jw,this)):this.F=g.Gg(this.jw,this.A,this)),c5(g5(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){c5(g5(this,"Send error: "+f.message)),k5(this,f)}};
g.h.jw=function(){"undefined"!=typeof g.hY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,g5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(g5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),j5(this))};
g.h.U=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),j5(this,!0));n5.Xa.U.call(this)};
g.h.iw=function(){this.ea()||(this.W||this.C||this.o?m5(this):this.uK())};
g.h.uK=function(){m5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<l5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Fa(this.l)?this.l:String(this.l)};
var l6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},k6={"'":"\\'"},gra={};g.h=t5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Oma)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var mqa={JN:"atp",UP:"ska",JP:"que",jP:"mus",TP:"sus",AO:"dsp",QP:"seq"};v5.prototype.hg=function(){var a=new v5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var P5,I5="",uqa=R5("loadCastFramework")||R5("loadCastApplicationFramework"),Nqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.y(X5,g.D);g.h=X5.prototype;g.h.lD=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.H)()+this.Wc:this.za=g.Gg(this.u,this.Wc)};
g.h.stop=function(){this.za&&(g.v.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.U=function(){this.stop();X5.Xa.U.call(this)};
g.h.mD=function(){this.l?(this.za=g.Gg(this.u,this.l-(0,g.H)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};Y5.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
Y5.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=Z5.prototype;g.h.bh=null;g.h.xe=!1;g.h.Wi=null;g.h.kt=null;g.h.Fi=null;g.h.Wh=null;g.h.Yf=null;g.h.Fg=null;g.h.uh=null;g.h.tc=null;g.h.kl=0;g.h.Be=null;g.h.mo=null;g.h.qg=null;g.h.Tj=-1;g.h.cA=!0;g.h.Qg=!1;g.h.bq=0;g.h.In=null;var f6={},d6={};g.h=Z5.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.dM=function(a){a=a.target;var b=this.In;b&&3==l5(a)?b.Pj():this.jB(a)};
g.h.jB=function(a){try{if(a==this.tc)a:{var b=l5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Md&&!g.pd(10)||g.Od&&!g.od("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!o5(this.tc))break a;this.Qg||4!=b||7==c||(8==c||0>=d?this.g.te(3):this.g.te(2));p6(this);var e=this.tc.getStatus();this.Tj=e;var f=o5(this.tc);(this.xe=200==e)?(4==b&&h6(this),this.u?(j6(this,b,f),g.Ch&&this.xe&&3==b&&(this.ba.ca(this.i,"tick",this.WL),this.i.start())):g6(this,f),this.xe&&!this.Qg&&(4==b?this.g.vn(this):(this.xe=
!1,c6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.qg=3,e6(13)):(this.qg=0,e6(14)),h6(this),i6(this))}}catch(k){this.tc&&o5(this.tc)}finally{}};
g.h.WL=function(){var a=l5(this.tc),b=o5(this.tc);this.kl<b.length&&(p6(this),j6(this,a,b),this.xe&&4!=a&&c6(this))};
g.h.uL=function(a){o6((0,g.x)(this.tL,this,a),0)};
g.h.tL=function(a){this.Qg||(p6(this),g6(this,a),c6(this))};
g.h.gz=function(a){o6((0,g.x)(this.sL,this,a),0)};
g.h.sL=function(a){this.Qg||(h6(this),this.xe=a,this.g.vn(this),this.g.te(4))};
g.h.cancel=function(){this.Qg=!0;h6(this)};
g.h.EL=function(){this.Wi=null;var a=(0,g.H)();0<=a-this.kt?(2!=this.Wh&&this.g.te(3),h6(this),this.qg=2,e6(18),i6(this)):n6(this,this.kt-a)};
g.h.getLastError=function(){return this.qg};g.h=t6.prototype;g.h.Yp=null;g.h.Cd=null;g.h.Jn=!1;g.h.hw=null;g.h.fm=null;g.h.Mq=null;g.h.Zp=null;g.h.ce=null;g.h.Af=-1;g.h.Sj=null;g.h.kj=null;g.h.connect=function(a){this.Zp=a;a=u6(this.g,null,this.Zp);e6(3);this.hw=(0,g.H)();var b=this.g.D;null!=b?(this.Sj=b[0],(this.kj=b[1])?(this.ce=1,v6(this)):(this.ce=2,x6(this))):(e5(a,"MODE","init"),this.Cd=new Z5(this,void 0,void 0,void 0),this.Cd.bh=this.Yp,b6(this.Cd,a,!1,null,!0),this.ce=0)};
g.h.sC=function(a){if(a)this.ce=2,x6(this);else{e6(4);var b=this.g;b.Ie=b.gg.Af;R6(b,9)}a&&this.te(2)};
g.h.yp=function(a){return this.g.yp(a)};
g.h.abort=function(){this.Cd&&(this.Cd.cancel(),this.Cd=null);this.Af=-1};
g.h.gw=function(){return!1};
g.h.az=function(a,b){this.Af=a.Tj;if(0==this.ce)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ie=this.Af;R6(c,2);return}this.Sj=c[0];this.kj=c[1]}else c=this.g,c.Ie=this.Af,R6(c,2);else if(2==this.ce)if(this.Jn)e6(7),this.Mq=(0,g.H)();else if("11111"==b){if(e6(6),this.Jn=!0,this.fm=(0,g.H)(),c=this.fm-this.hw,!g.Md||g.pd(10)||500>c)this.Af=200,this.Cd.cancel(),e6(12),w6(this.g,this,!0)}else e6(8),this.fm=this.Mq=(0,g.H)(),this.Jn=!1};
g.h.vn=function(){this.Af=this.Cd.Tj;if(this.Cd.xe)0==this.ce?this.kj?(this.ce=1,v6(this)):(this.ce=2,x6(this)):2==this.ce&&((!g.Md||g.pd(10)?!this.Jn:200>this.Mq-this.fm)?(e6(11),w6(this.g,this,!1)):(e6(12),w6(this.g,this,!0)));else{0==this.ce?e6(9):2==this.ce&&e6(10);var a=this.g;this.Cd.getLastError();a.Ie=this.Af;R6(a,2)}};
g.h.Sk=function(){return this.g.Sk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.te=function(a){this.g.te(a)};g.h=y6.prototype;g.h.xj=null;g.h.yd=null;g.h.Sb=null;g.h.Xp=null;g.h.hm=null;g.h.xu=null;g.h.sm=null;g.h.zk=0;g.h.KH=0;g.h.Tc=null;g.h.mg=null;g.h.nf=null;g.h.Vg=null;g.h.gg=null;g.h.ko=null;g.h.ji=-1;g.h.Nw=-1;g.h.Ie=-1;g.h.Qh=0;g.h.Jh=0;g.h.Rg=8;var S6=new g.Sf;g.y(z6,g.sf);g.y(A6,g.sf);g.y(B6,g.sf);g.h=y6.prototype;g.h.connect=function(a,b,c,d,e){e6(0);this.Xp=b;this.xj=c||{};d&&g.Ea(e)&&(this.xj.OSID=d,this.xj.OAID=e);this.A?(o6((0,g.x)(this.Qu,this,a),100),H6(this)):this.Qu(a)};
g.h.Qu=function(a){this.gg=new t6(this);this.gg.Yp=null;this.gg.i=this.u;this.gg.connect(a)};
g.h.gw=function(){return 0==this.g};
g.h.fz=function(a){this.mg=null;M6(this,a)};
g.h.ez=function(){this.nf=null;this.Sb=new Z5(this,this.l,"rpc",this.C);this.Sb.bh=null;this.Sb.bq=0;var a=this.xu.clone();g.Vm(a,"RID","rpc");g.Vm(a,"SID",this.l);g.Vm(a,"CI",this.ko?"0":"1");g.Vm(a,"AID",this.ji);D6(this,a);if(!g.Md||g.pd(10))g.Vm(a,"TYPE","xmlhttp"),b6(this.Sb,a,!0,this.sm,!1);else{g.Vm(a,"TYPE","html");var b=this.Sb,c=!!this.sm;b.Wh=3;b.Yf=d5(a.clone());m6(b,c)}};
g.h.az=function(a,b){if(0!=this.g&&(this.Sb==a||this.yd==a))if(this.Ie=a.Tj,this.yd==a&&3==this.g)if(7<this.Rg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ma(c)&&3==c.length)if(0==c[0])a:{if(!this.nf){if(this.Sb)if(this.Sb.Fi+3E3<this.yd.Fi)I6(this),this.Sb.cancel(),this.Sb=null;else break a;P6(this);e6(19)}}else this.Nw=c[1],0<this.Nw-this.ji&&37500>c[2]&&this.ko&&0==this.Jh&&!this.Vg&&(this.Vg=o6((0,g.x)(this.mI,this),6E3));else R6(this,11)}else b!=gra.fO.g&&R6(this,11);else if(this.Sb==a&&
I6(this),!g.xb(b)){c=this.u.parse(b);g.Ma(c);for(var d=0;d<c.length;d++){var e=c[d];this.ji=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.sm=e[2],e=e[3],null!=e?this.Rg=e:this.Rg=6,this.g=3,this.Tc&&this.Tc.Ku(),this.xu=u6(this,this.Sk()?this.sm:null,this.Xp),N6(this)):"stop"==e[0]&&R6(this,7):3==this.g&&("stop"==e[0]?R6(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.Ju(e),this.Jh=0)}}};
g.h.mI=function(){null!=this.Vg&&(this.Vg=null,this.Sb.cancel(),this.Sb=null,P6(this),e6(20))};
g.h.vn=function(a){if(this.Sb==a){I6(this);this.Sb=null;var b=2}else if(this.yd==a)this.yd=null,b=1;else return;this.Ie=a.Tj;if(0!=this.g)if(a.xe)1==b?(b=(0,g.H)()-a.Fi,S6.dispatchEvent(new A6(S6,a.uh?a.uh.length:0,b,this.Qh)),G6(this),this.o.length=0):N6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ie)){if(d=1==b)this.yd||this.mg||1==this.g||2<=this.Qh?d=!1:(this.mg=o6((0,g.x)(this.fz,this,a),O6(this,this.Qh)),this.Qh++,d=!0);d=!(d||2==b&&P6(this))}if(d)switch(c){case 1:R6(this,
5);break;case 4:R6(this,10);break;case 3:R6(this,6);break;case 7:R6(this,12);break;default:R6(this,2)}}};
g.h.LC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.IM=function(a){a?e6(2):(e6(1),Q6(this,8))};
g.h.yp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new n5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.te=function(a){S6.dispatchEvent(new B6(S6,a))};
g.h.Sk=function(){return!(!g.Md||g.pd(10))};
g.h=T6.prototype;g.h.Ku=function(){};
g.h.Ju=function(){};
g.h.Iu=function(){};
g.h.kp=function(){};
g.h.Gv=function(){return{}};
g.h.isActive=function(){return!0};g.y(U6,g.D);g.h=U6.prototype;g.h.mL=function(){this.Wc=Math.min(3E5,2*this.Wc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Wc+15E3*Math.random();g.bo(this.g,a);this.i=(0,g.H)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Wc=5E3};g.y(V6,T6);g.h=V6.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Kf=function(a){return this.l.eh(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.fb||(this.fb=!0,g.qf(this.l),W6(this),g.qf(this.i),this.i=null)};
g.h.ea=function(){return this.fb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new y6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ji):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):X6(this)&&J6(this.g,c)};
g.h.Ku=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)J6(this.g,a[b])}this.N("handlerOpened")};
g.h.Iu=function(a){var b=2==a&&401==this.g.Ie;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.kp=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.Gv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.fc(a,this.u);return a};
g.h.Ju=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),F6(this.g)):this.N("handlerMessage",new yqa(a[0],a[1]))};
g.h.mM=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.yd&&b++;0==b&&this.connect(this.u,this.o)};Y6.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Y6.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
Y6.prototype.u=function(a){a(Error("request timed out"))};var Eqa=(0,g.H)(),c7=null,g7=Array(50),f7=-1,h7=!1;g.y(i7,g.P);i7.prototype.Id=function(){return this.g};
i7.prototype.contains=function(a){return!!D5(this.g,a)};
i7.prototype.get=function(a){return a?E5(this.g,a):null};
i7.prototype.info=function(a){e7(this.C,a)};g.t(k7,g.P);g.h=k7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.mB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Kp(this.za),this.za=NaN)};
g.h.U=function(){this.stop();g.P.prototype.U.call(this)};
g.h.mB=function(){this.za=NaN;this.g=g.Fq(Z6(this.A,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.jN,this),onError:(0,g.x)(this.iN,this),ie:(0,g.x)(this.kN,this)})};
g.h.jN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new w5(c))};
g.h.iN=function(a){this.g=null;a.status&&404==a.status?this.i>=s9.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=s9[this.i],this.za=g.Ip((0,g.x)(this.mB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.kN=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var s9=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.y(m7,i7);g.h=m7.prototype;g.h.start=function(){l7(this)&&this.N("screenChange");!g.gt("yt-remote-lounge-token-expiration")&&n7(this);g.Kp(this.i);this.i=g.Ip((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){l7(this);j7(this,a);o7(this,!1);this.N("screenChange");b(a);a.token||n7(this)};
g.h.remove=function(a,b){var c=l7(this);Gqa(this,a)&&(o7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.eo=function(a,b,c,d){var e=l7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,o7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.U=function(){g.Kp(this.i);m7.Xa.U.call(this)};
g.h.wD=function(a){l7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}o7(this,!b);b&&e7(this.C,"Missed "+b+" lounge tokens.")};
g.h.vD=function(a){e7(this.C,"Requesting lounge tokens failed: "+a)};g.t(q7,g.P);g.h=q7.prototype;g.h.start=function(){var a=parseInt(g.gt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.H)()-144E5<a?0:a)?t7(this):(this.o=(0,g.H)()+3E5,g.ft("yt-remote-fast-check-period",this.o),this.os())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){p7("Updating availability on schedule.");var a=this.A(),b=g.Mb(this.g,function(c,d){return c&&!!E5(a,d)},this);
s7(this,b)};
g.h.U=function(){g.Kp(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.P.prototype.U.call(this)};
g.h.os=function(){g.Kp(this.l);this.l=NaN;this.i&&this.i.abort();var a=u7(this);if(q5(a)){var b=Z6(this.u,"/pairing/get_screen_availability");this.i=$6(this.u,b,{lounge_token:g.Sb(a).join(",")},(0,g.x)(this.QK,this,a),(0,g.x)(this.PK,this))}else s7(this,{}),t7(this)};
g.h.QK=function(a,b){this.i=null;var c=g.Sb(u7(this));if(g.sb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;s7(this,d);t7(this)}else this.Hb("Changing Screen set during request."),this.os()};
g.h.PK=function(a){this.Hb("Screen availability failed: "+a);this.i=null;t7(this)};
g.h.Hb=function(a){e7("OnlineScreenService",a)};g.y(v7,i7);g.h=v7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.eo=function(a,b,c,d){this.l.contains(a)?this.l.eo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,e7(this.C,a),d(Error(a)))};
g.h.Id=function(a){return a?this.g:g.gb(this.g,(0,g.Yd)(this.o,function(b){return!this.contains(b)},this))};
g.h.nB=function(){return(0,g.Yd)(this.Id(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.oB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new k7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.qf(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.mN=function(a,b,c,d){g.Fq(Z6(this.A,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new w5(f.screen||{});if(!k.name||y7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);y7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
ie:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.qf(this.l);g.qf(this.i);v7.Xa.U.call(this)};
g.h.ED=function(){z7(this);this.N("screenChange");this.i.update()};
v7.prototype.dispose=v7.prototype.dispose;g.y(B7,g.P);g.h=B7.prototype;g.h.xn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Ld=function(a){this.ea()||(a&&C7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){e7(this.P,a)};
g.h.qB=function(){return null};
g.h.Bs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){C7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Bs("");B7.Xa.U.call(this)};g.y(E7,B7);g.h=E7.prototype;g.h.As=function(a){if(this.g){if(this.g==a)return;C7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Kqa(this)};
g.h.li=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Ld()},this),(0,g.x)(function(){this.Ld(Error("Failed to stop receiver app."))},this)):this.Ld(Error("Stopping cast device witout session."))};
g.h.Bs=g.Ja;g.h.U=function(){this.info("disposeInternal");g.Kp(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;E7.Xa.U.call(this)};
g.h.PL=function(a,b){if(!this.ea())if(b){var c=s5(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":D7(this,c.screenId);break;default:C7(this,"Unknown youtube message: "+d)}}else C7(this,"Unable to parse message.")}else C7(this,"No data in message.")};
g.h.Wv=function(a,b,c,d){x7(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(C7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Ip((0,g.x)(this.Wv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.qB=function(){return this.g};
g.h.nN=function(a){this.ea()||a||(C7(this,"Cast session died."),this.Ld())};g.y(F7,B7);g.h=F7.prototype;g.h.As=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.li=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ja;g.Kp(this.A);this.o?this.o.stop((0,g.x)(this.Ld,this,null),(0,g.x)(this.Ld,this,"Failed to stop DIAL device.")):this.Ld()};
g.h.U=function(){this.g();this.g=g.Ja;g.Kp(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;F7.Xa.U.call(this)};
g.h.qN=function(a){this.ea()||a||(C7(this,"DIAL session died."),this.g(),this.g=g.Ja,this.Ld())};
g.h.oq=function(a){this.H=C5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,H7(this));a(b);G7(this)}else this.C=(0,g.x)(function(){g.Kp(this.A);this.C=g.Ja;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,H7(this));a(c);G7(this)},this),this.A=g.Ip((0,g.x)(function(){this.C()},this),100)};
g.h.aE=function(a,b,c){x7(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.xn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.oq(b,c)},this),(0,g.x)(function(d){C7(this,"Failed to get DIAL screen: "+d);
this.oq(b,c)},this))};g.y(I7,B7);I7.prototype.stop=function(){this.Ld()};
I7.prototype.As=g.Ja;I7.prototype.li=function(){g.Kp(this.g);this.g=NaN;var a=E5(this.F.Id(),this.i.label);a?this.xn(a):this.Ld(Error("No such screen"))};
I7.prototype.U=function(){g.Kp(this.g);this.g=NaN;I7.Xa.U.call(this)};g.y(J7,g.P);g.h=J7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.zK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.cz,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.NI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),Bqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.pB,this)),this.l=O7(this),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(k){this.Hb("Failed to set initial custom receivers: "+g.Kg(k))},this)),this.N("yt-remote-cast2-availability-change",M7(this)),b(!0))},this),(0,g.x)(function(k){this.Hb("Failed to initialize API: "+g.Kg(k));
b(!1)},this))};
g.h.vM=function(a,b){L7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)L7("Unsetting old screen status: "+this.g.i.friendlyName),N7(this,null)}if(a&&b){if(!this.g){c=E5(this.i.Id(),a);if(!c){L7("setConnectedScreenStatus: Unknown screen.");return}var d=K7(this,c);d||(L7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ja,(0,g.x)(function(e){this.Hb("Failed to set initial custom receivers: "+g.Kg(e))},this)));
L7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);N7(this,new I7(this.i,d),!0)}this.g.Bs(b)}else L7("setConnectedScreenStatus: no screen.")};
g.h.wM=function(a){this.ea()?this.Hb("Setting connection data on disposed cast v2"):this.g?this.g.li(a):this.Hb("Setting connection data without a session")};
g.h.pN=function(){this.ea()?this.Hb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),N7(this,null)):L7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.cz,this),(0,g.x)(this.VK,this))};
g.h.U=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.pB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.w("yt.mdx.remote.debug.handlers_")||[],a7);g.qf(this.g);J7.Xa.U.call(this)};
g.h.Hb=function(a){e7("Controller",a)};
g.h.dz=function(a,b){this.g==a&&(b||N7(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.vK=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),L7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)L7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{L7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:N7(this,
new I7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:N7(this,new F7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:N7(this,new E7(this.i,a));break;default:this.Hb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Hb("Stopping receiver w/o session: "+a.friendlyName)}else this.Hb("onReceiverAction_ called without receiver.")};
g.h.NI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Hb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return L7("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);N7(this,new F7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.aE,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.oq,b))};
g.h.cz=function(a){if(!this.ea()){L7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)L7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),N7(this,new E7(this.i,b),!0);else{this.Hb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=E5(this.i.Id(),c.label);d&&x5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(L7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new E7(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.dz,this,this.g)),this.g.li(null));this.g.As(a)}}};
g.h.oN=function(){return this.g?this.g.qB():null};
g.h.VK=function(a){this.ea()||(this.Hb("Failed to estabilish a session: "+g.Kg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&N7(this,null))};
g.h.zK=function(a){L7("Receiver availability updated: "+a);if(!this.ea()){var b=M7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;M7(this)!=b&&this.N("yt-remote-cast2-availability-change",M7(this))}};
g.h.pB=function(){this.ea()||(this.l=O7(this),L7("Updating custom receivers: "+g.Kg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(){this.Hb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",M7(this)))};
J7.prototype.setLaunchParams=J7.prototype.wM;J7.prototype.setConnectedScreenStatus=J7.prototype.vM;J7.prototype.stopSession=J7.prototype.pN;J7.prototype.getCastSession=J7.prototype.oN;J7.prototype.requestSession=J7.prototype.requestSession;J7.prototype.init=J7.prototype.init;J7.prototype.dispose=J7.prototype.dispose;var X7=[];e8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";f8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Je=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
e8.prototype.isAdPlaying=function(){return 1081==this.playerState};
e8.prototype.getDuration=function(){return this.u?this.D+g8(this):this.D};
e8.prototype.clone=function(){return new e8(k8(this))};g.t(n8,g.P);g.h=n8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ja,v8(this,"play")):t8(this,"play"),s8(this,1,i8(o8(this))),this.N("remotePlayerChange")):q8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ja,v8(this,"pause")):t8(this,"pause"),s8(this,2,i8(o8(this))),this.N("remotePlayerChange")):q8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=o8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ja,v8(this,"seekTo",{newTime:a}))}else t8(this,"seekTo",{newTime:a});s8(this,3,a);this.N("remotePlayerChange")}else q8(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ja,v8(this,"stopVideo")):t8(this,"stopVideo");var a=o8(this);a.index=-1;a.videoId="";f8(a);r8(this,a);this.N("remotePlayerChange")}else q8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=o8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){e7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Hb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){e7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Hb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);t8(this,"setVolume",e)}c.muted=b;c.volume=a;r8(this,c)}else q8(this,g.Sa(this.setVolume,a,b))};
g.h.pA=function(a,b){if(1==this.g){var c=o8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kg(b.style),g.fc(d,c.g));t8(this,"setSubtitlesTrack",d);r8(this,c)}else q8(this,g.Sa(this.pA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();t8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=o8(this);d.audioTrackId=c;r8(this,d)}else q8(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=o8(this);c=c||0;var m={videoId:a,currentIndex:c};j8(l,a,c);g.Ea(b)&&(h8(l,b),m.currentTime=b);g.Ea(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kg(k));t8(this,"setPlaylist",m);d||r8(this,l)};
g.h.En=function(a,b){if(1==this.g){if(a&&b){var c=o8(this);j8(c,a,b);r8(this,c)}t8(this,"previous")}else q8(this,g.Sa(this.En,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=o8(this);j8(c,a,b);r8(this,c)}t8(this,"next")}else q8(this,g.Sa(this.nextVideo,a,b))};
g.h.hv=function(){1==this.g?t8(this,"dismissAutoplay"):q8(this,this.hv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.P.prototype.dispose.call(this)};
g.h.U=function(){p8(this);this.o=null;this.u.clear();m8(this,null);g.P.prototype.U.call(this)};
g.h.nt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.sK=function(a,b){this.N(a,b)};
g.h.sI=function(a){if(!a)this.Ck(null),m8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=o8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)e7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,r8(this,b)}};
g.h.Ck=function(a){e7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),u8(this),this.N("remotePlayerChange")};
g.h.rI=function(a){a?(u8(this),this.N("remotePlayerChange")):this.Ck(null)};
g.h.Ts=function(){t8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.GI=function(){var a=a8();a&&m8(this,a)};
g.h.Hb=function(a){e7("CP",a)};g.t(w8,g.P);g.h=w8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ea(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ea(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;h8(this.Oa,m);this.o="UNSUPPORTED";x8("Connecting with setPlaylist and params: "+g.Kg(l));this.g.connect({method:"setPlaylist",
params:g.Kg(l)},a,L5())}else x8("Connecting without params"),this.g.connect({},a,L5());Rqa(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),y8(this,3));g.P.prototype.dispose.call(this)};
g.h.U=function(){z8(this);B8(this);A8(this);g.Kp(this.C);this.C=NaN;g.Kp(this.D);this.D=NaN;this.l=null;g.Or(this.P);this.P.length=0;this.g.dispose();g.P.prototype.U.call(this);this.o=this.A=this.i=this.Oa=this.g=null};
g.h.pD=function(){this.Nh(2)};
g.h.wI=function(){x8("Channel opened");this.I&&(this.I=!1,A8(this),this.H=g.Ip((0,g.x)(function(){x8("Timing out waiting for a screen.");this.Nh(1)},this),15E3));
sqa(zqa(this.g),this.M)};
g.h.tI=function(){x8("Channel closed");isNaN(this.u)?O5(!0):O5();this.dispose()};
g.h.uI=function(a){O5();isNaN(this.Hj())?(x8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,x8("Channel error: "+a+" with reconnection in "+this.Hj()+" ms"),y8(this,2))};
g.h.vI=function(a){a.params?x8("Received: action="+a.action+", params="+g.Kg(a.params)):x8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=s5(a.params.devices);this.i=(0,g.B)(a,function(c){return new v5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
E8(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
E8(this,!1);break;case "remoteConnected":var b=new v5(s5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||hqa(this.i,b);
break;case "remoteDisconnected":b=new v5(s5(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":F8(this,a);break;case "nowPlaying":Uqa(this,a);break;case "onStateChange":G8(this,a);break;case "onAdStateChange":Vqa(this,a);break;case "onVolumeChanged":Wqa(this,a);break;case "onSubtitlesTrackChanged":Tqa(this,a);break;case "nowAutoplaying":Xqa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.N("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":Yqa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:x8("Unrecognized action: "+a.action)}};
g.h.jM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&C8(this,"getNowPlaying")}};
g.h.fD=function(){var a=3;this.ea()||(a=0,isNaN(this.Hj())?X6(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Nh=function(a){x8("Disconnecting with "+a);z8(this);this.N("beforeDisconnect",a);1==a&&O5();W6(this.g,a);this.dispose()};
g.h.eD=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),j8(a,this.l,a.index));return k8(a)};
g.h.xM=function(a){var b=new e8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Kp(this.C),this.C=g.Ip((0,g.x)(this.jM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&i8(this.Oa)==i8(b)&&g.Kg(this.Oa.g)==g.Kg(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.z)(c,function(d){this.N(d)},this)};
g.h.Tv=function(){var a=this.g.A.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Hj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.H)():NaN};
g.h.XC=function(){return this.o||"UNSUPPORTED"};
g.h.YC=function(){return this.A||""};
g.h.hN=function(){if(!isNaN(this.Hj())){var a=this.g.i;g.co(a.g);a.start()}};
g.h.qM=function(a,b){C8(this,a,b);D8(this)};
w8.prototype.subscribe=w8.prototype.subscribe;w8.prototype.unsubscribeByKey=w8.prototype.Kf;w8.prototype.getProxyState=w8.prototype.fD;w8.prototype.disconnect=w8.prototype.Nh;w8.prototype.getPlayerContextData=w8.prototype.eD;w8.prototype.setPlayerContextData=w8.prototype.xM;w8.prototype.getOtherConnectedRemoteId=w8.prototype.Tv;w8.prototype.getReconnectTimeout=w8.prototype.Hj;w8.prototype.getAutoplayMode=w8.prototype.XC;w8.prototype.getAutoplayVideoId=w8.prototype.YC;w8.prototype.reconnect=w8.prototype.hN;
w8.prototype.sendMessage=w8.prototype.qM;g.t(H8,i7);g.h=H8.prototype;g.h.Id=function(a){return this.Vc.$_gs(a)};
g.h.contains=function(a){return!!this.Vc.$_c(a)};
g.h.get=function(a){return this.Vc.$_g(a)};
g.h.start=function(){this.Vc.$_st()};
g.h.add=function(a,b,c){this.Vc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Vc.$_r(a,b,c)};
g.h.eo=function(a,b,c,d){this.Vc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.i.length;a<b;++a)this.Vc.$_ubk(this.i[a]);this.i.length=0;this.Vc=null;i7.prototype.U.call(this)};
g.h.lN=function(){this.N("screenChange")};
g.h.XJ=function(){this.N("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.mN;v7.prototype.$_gsppc=v7.prototype.oB;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.eo;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.Id;v7.prototype.$_gos=v7.prototype.nB;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.Kf;var c9=null,b9=!1,I8=null,J8=null,Z8=null,N8=[];g.t(d9,g.D);g.h=d9.prototype;
g.h.U=function(){g.D.prototype.U.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Zy,this);this.g.unsubscribe("remotePlayerChange",this.Ek,this);this.g.unsubscribe("remoteQueueChange",this.yn,this);this.g.unsubscribe("autoplayUpNext",this.Dy,this);this.g.unsubscribe("previousNextChange",this.Wy,this);this.g.unsubscribe("nowAutoplaying",this.Sy,this);this.g.unsubscribe("autoplayDismissed",this.Cy,this);this.g=this.u=null};
g.h.zx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(h9(this)){if(!o8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==o8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Pj(c[0],c[1]);break;case "control_subtitles_set_track":i9(this,c[0]);break;case "control_set_audio_track":c=c[0],h9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();j9(this,0==c?void 0:c);break;case "control_seek":j9(this,c[0]);break;case "control_subtitles_set_track":i9(this,c[0]);break;case "control_set_audio_track":c=c[0],h9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.qI=function(a){this.I.lD(a)};
g.h.SM=function(a){this.zx("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.CA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||i9(this,a)};
g.h.Oy=function(a){if(h9(this)){this.g.unsubscribe("remotePlayerChange",this.Ek,this);var b=Math.round(a.volume);a=!!a.muted;var c=o8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.Ek,this)}};
g.h.rJ=function(){g.Yb(this.C)||k9(this,this.C);this.D=!1};
g.h.Zy=function(a,b){this.A.stop();2==b&&this.BA()};
g.h.Ek=function(){if(h9(this)){this.o.stop();var a=o8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Lm=1;break;case 1082:case 1083:this.u.Lm=0;break;default:this.u.Lm=-1}switch(a.playerState){case 1081:case 1:f9(this,new g.iC(8));this.AA();break;case 1085:case 3:f9(this,new g.iC(9));break;case 1083:case 0:f9(this,new g.iC(2));this.H.stop();e9(this,this.i.getVideoData().lengthSeconds);break;case 1084:f9(this,new g.iC(4));break;case 2:f9(this,new g.iC(4));e9(this,i8(a));
break;case -1:f9(this,new g.iC(64));break;case -1E3:f9(this,new g.iC(128,{errorCode:"mdx.remoteerror",message:"\u041e\u0432\u0430\u0458 \u0432\u0438\u0434\u0435\u043e \u043d\u0438\u0458\u0435 \u0434\u043e\u0441\u0442\u0443\u043f\u0430\u043d \u0437\u0430 \u0434\u0430\u0459\u0438\u043d\u0441\u043a\u0443 \u0440\u0435\u043f\u0440\u043e\u0434\u0443\u043a\u0446\u0438\u0458\u0443."}))}a=o8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&
a.kind==b.kind:1)||(this.C=a,k9(this,a));a=o8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.aB()}else g9(this)};
g.h.Wy=function(){this.i.N("mdxpreviousnextchange")};
g.h.yn=function(){h9(this)||g9(this)};
g.h.rC=function(){this.g.hv()};
g.h.Dy=function(a){a&&(a=g.Fq("/watch_queue_ajax",{method:"GET",Dc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.xL,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.xL=function(a,b){var c=new g.VA(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Sy=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.Cy=function(){this.i.N("mdxautoplaycanceled")};
g.h.NF=function(a,b){-1==o8(this.g).playerState?j9(this,a):b&&this.g.seekTo(a)};
g.h.aB=function(){if(h9(this)){var a=o8(this.g);this.l.Ka(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.Oy)}};
g.h.AA=function(){this.o.stop();if(!this.g.ea()){var a=o8(this.g);1==a.playerState&&f9(this,new g.iC(8));e9(this,i8(a));this.o.start()}};
g.h.BA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(m9,g.W);m9.prototype.o=function(){u5("mdx-privacy-popup-cancel");this.l.hide()};
m9.prototype.A=function(){u5("mdx-privacy-popup-confirm");this.l.hide()};g.t(o9,g.W);o9.prototype.u=function(a){n9(this,a.state)};g.t(p9,g.DT);p9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.ub(a,this.A,this),g.ET(this,(0,g.B)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.se(this.A(a)),this.enable(!0)):this.enable(!1)};
p9.prototype.A=function(a){return a.key};
p9.prototype.re=function(a){return"cast-selector-receiver"==a?"\u041f\u0440\u0435\u0431\u0430\u0446\u0438\u2026":this.F[a].name};
p9.prototype.Ic=function(a){g.DT.prototype.Ic.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.ib()};g.t(q9,g.yK);g.h=q9.prototype;
g.h.create=function(){cra(g.Fy(g.X(this.player)));this.o.push(g.Pp("yt-remote-before-disconnect",this.nI,this));this.o.push(g.Pp("yt-remote-connection-change",this.AK,this));this.o.push(g.Pp("yt-remote-receiver-availability-change",this.Xy,this));this.o.push(g.Pp("yt-remote-auto-connect",this.yK,this));this.o.push(g.Pp("yt-remote-receiver-resumed",this.xK,this));this.o.push(g.Pp("mdx-privacy-popup-confirm",this.ZL,this));this.o.push(g.Pp("mdx-privacy-popup-cancel",this.YL,this));this.Xy()};
g.h.load=function(){this.player.cancelPlayback();g.yK.prototype.load.call(this);this.u=new d9(this,this.player,this.g);var a=(a=a9())?a.currentTime:0;var b=Y8()?new n8(T8(),void 0):null;0==a&&b&&(a=i8(o8(b)));0!=a&&this.Kc(a);l9(this,this.mk,this.mk);g.DX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.rf(this.u,this.g);this.g=this.u=null;g.yK.prototype.unload.call(this);g.DX(this.player.app,5)};
g.h.U=function(){g.Qp(this.o);g.yK.prototype.U.call(this)};
g.h.Xe=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.zx.apply(this.u,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.Lm};
g.h.hD=function(){return this.loaded?this.u.suggestion:null};
g.h.Je=function(){return this.g?o8(this.g).Je:!1};
g.h.hasNext=function(){return this.g?o8(this.g).hasNext:!1};
g.h.Kc=function(a,b){this.H=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.H};
g.h.getProgressState=function(){var a=o8(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.dc():!a.isAdPlaying()&&this.player.dc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+g8(a):a.l,isAtLiveHead:1>=(a.u?a.i+g8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+g8(a):a.i,seekableStart:0<a.o?a.o+
g8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.En=function(){this.g&&this.g.En()};
g.h.nI=function(a){1==a&&(this.C=this.g?o8(this.g):null)};
g.h.AK=function(){var a=Y8()?new n8(T8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.C=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.C)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,i8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Xy=function(){this.A=[this.i].concat(dra());var a=U8()||this.i;r9(this,a);this.player.la("onMdxReceiversChange")};
g.h.yK=function(){var a=U8();r9(this,a)};
g.h.xK=function(){this.l=U8()};
g.h.ZL=function(){this.D=!0;b9=!1;c9&&W8(c9,1);c9=null};
g.h.YL=function(){this.D=!1;r9(this,this.i);this.l=this.i;b9=!1;c9=null;this.player.playVideo()};
g.h.xc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?c8():r9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&c8(),!0):!1}};
g.h.Ts=function(){this.g.Ts()};
g.h.Lb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.UU.remote=q9;})(_yt_player);
